ANIMA: animaODFProbabilisticTractography.cxx File Reference
animaODFProbabilisticTractography.cxx File Reference
#include <animaODFProbabilisticTractographyImageFilter.h>
#include <animaGradientFileReader.h>
#include <itkTimeProbe.h>
#include <tclap/CmdLine.h>
#include <itkImageFileReader.h>
#include <itkCommand.h>
#include <animaFibersWriter.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char *argv[])
Function Documentation
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 13 of file animaODFProbabilisticTractography.cxx.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 19 of file animaODFProbabilisticTractography.cxx.
References eventCallback(), anima::FibersWriter::SetFileName(), anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName(), anima::FibersWriter::SetInputData(), and anima::FibersWriter::Update().