ANIMA: anima::LTSWTransformAgregator< NDimensions > Class Template Reference
anima::LTSWTransformAgregator< NDimensions > Class Template Reference
#include <animaLTSWTransformAgregator.h>
Public Types
typedef
Superclass::BaseInputTransformType BaseInputTransformType
typedef itk::AffineTransform
< ScalarType, NDimensions > BaseOutputTransformType
typedef
Superclass::InternalScalarType InternalScalarType
typedef Superclass::PointType PointType
typedef Superclass::ScalarType ScalarType
typedef BaseTransformAgregator
< NDimensions > Superclass
Public Types inherited from anima::BaseTransformAgregator< NDimensions >
typedef
BaseInputTransformType::Pointer BaseInputTransformPointer
typedef itk::Transform
< InternalScalarType,
NDimensions, NDimensions > BaseInputTransformType
typedef itk::Transform
< ScalarType, NDimensions,
NDimensions > BaseOutputTransformType
typedef double InternalScalarType
typedef itk::Point
< InternalScalarType,
NDimensions > PointType
typedef itk::ImageRegion
< NDimensions > RegionType
typedef double ScalarType
enum TRANSFORM_TYPE {
TRANSLATION,
RIGID,
AFFINE,
SVF
}
Public Member Functions
LTSWTransformAgregator ()
void SeStoppingThreshold (double stopThr)
void SetLTSCut (double ltsCut)
virtual bool Update ()
virtual ~LTSWTransformAgregator ()
Public Member Functions inherited from anima::BaseTransformAgregator< NDimensions >
BaseTransformAgregator ()
PointType & GetInputOrigin (unsigned int i)
std::vector< PointType > & GetInputOrigins ()
std::vector< RegionType > & GetInputRegions ()
BaseInputTransformType * GetInputTransform (unsigned int i)
std::vector
< BaseInputTransformPointer > & GetInputTransforms ()
TRANSFORM_TYPE GetInputTransformType ()
InternalScalarType GetInputWeight (unsigned int i)
std::vector< InternalScalarType > & GetInputWeights ()
BaseOutputTransformType * GetOutput ()
TRANSFORM_TYPE GetOutputTransformType ()
void SetInputOrigins (const std::vector< PointType > &inputOrigins)
void SetInputRegions (const std::vector< RegionType > &inputRegions)
void SetInputTransforms (std::vector< BaseInputTransformPointer > &inputTransforms)
void SetInputTransformType (TRANSFORM_TYPE name)
void SetInputWeight (unsigned int i, double w)
void SetInputWeights (const std::vector< InternalScalarType > &weights)
void SetOutputTransformType (TRANSFORM_TYPE name)
void SetUpToDate (bool value)
virtual ~BaseTransformAgregator ()
Additional Inherited Members
Protected Member Functions inherited from anima::BaseTransformAgregator< NDimensions >
void SetOutput (BaseOutputTransformType *output)
Detailed Description
template<unsigned int NDimensions = 3>
class anima::LTSWTransformAgregator< NDimensions >
Definition at line 15 of file animaLTSWTransformAgregator.h.
Member Typedef Documentation
template<unsigned int NDimensions = 3> typedef Superclass::BaseInputTransformType anima::LTSWTransformAgregator< NDimensions >::BaseInputTransformType
Definition at line 21 of file animaLTSWTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef itk::AffineTransform<ScalarType,NDimensions> anima::LTSWTransformAgregator< NDimensions >::BaseOutputTransformType
Definition at line 23 of file animaLTSWTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::InternalScalarType anima::LTSWTransformAgregator< NDimensions >::InternalScalarType
Definition at line 24 of file animaLTSWTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::PointType anima::LTSWTransformAgregator< NDimensions >::PointType
Definition at line 20 of file animaLTSWTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::ScalarType anima::LTSWTransformAgregator< NDimensions >::ScalarType
Definition at line 22 of file animaLTSWTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef BaseTransformAgregator<NDimensions> anima::LTSWTransformAgregator< NDimensions >::Superclass
Definition at line 19 of file animaLTSWTransformAgregator.h.
Constructor & Destructor Documentation
template<unsigned int NDimensions> anima::LTSWTransformAgregator< NDimensions >::LTSWTransformAgregator ()
Definition at line 15 of file animaLTSWTransformAgregator.hxx.
template<unsigned int NDimensions = 3> virtual anima::LTSWTransformAgregator< NDimensions >::~LTSWTransformAgregator () inline virtual
Definition at line 27 of file animaLTSWTransformAgregator.h.
Member Function Documentation
template<unsigned int NDimensions = 3> void anima::LTSWTransformAgregator< NDimensions >::SeStoppingThreshold (double stopThr) inline
Definition at line 32 of file animaLTSWTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::SetUpToDate().
template<unsigned int NDimensions = 3> void anima::LTSWTransformAgregator< NDimensions >::SetLTSCut (double ltsCut) inline
Definition at line 31 of file animaLTSWTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::SetUpToDate().
Referenced by anima::PyramidalBlockMatchingBridge< ImageDimension >::Update().
template<unsigned int NDimensions> bool anima::LTSWTransformAgregator< NDimensions >::Update () virtual
Implements anima::BaseTransformAgregator< NDimensions >.
Definition at line 24 of file animaLTSWTransformAgregator.hxx.
The documentation for this class was generated from the following files:
animaLTSWTransformAgregator.h
animaLTSWTransformAgregator.hxx