ANIMA: anima::DTIProbabilisticTractographyImageFilter Class Reference
anima::DTIProbabilisticTractographyImageFilter Class Reference
#include <animaDTIProbabilisticTractographyImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef vnl_matrix< double > MatrixFreeType
typedef itk::SmartPointer< Self > Pointer
typedef
DTIProbabilisticTractographyImageFilter Self
typedef
BaseProbabilisticTractographyImageFilter Superclass
Public Types inherited from anima::BaseProbabilisticTractographyImageFilter
enum ColinearityDirectionType {
Center = 0,
Outward,
Top,
Bottom,
Left,
Right,
Front,
Back
}
Which direction should the very first direction point to? (used in conjunction with InitialDirectionMode) Center: towards gravity center Outward: outward from gravity center Top: Image top (z axis) Bottom: Image bottom (reverse z axis) ...
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef std::vector< Vector3DType > DirectionVectorType
typedef std::vector
< InterpolatorPointerType > DWIInterpolatorPointerVectorType
typedef std::vector< FiberType > FiberProcessVectorType
typedef std::vector< PointType > FiberType
typedef float ImageScalarType
typedef MaskImageType::IndexType IndexType
enum InitialDirectionModeType {
Colinear = 0,
Weight
}
Tells how to choose the very first direction of each particle Colinear: Most colinear to colinear direction specified (ColinearityDirectionType) Weight: Model direction with the highest weight.
typedef itk::Image
< ImageScalarType, 4 > Input4DImageType
typedef InputImageType::Pointer InputImagePointerType
typedef std::vector
< InputImagePointerType > InputImagePointerVectorType
typedef itk::Image
< ImageScalarType, 3 > InputImageType
typedef InterpolatorType::Pointer InterpolatorPointerType
typedef
anima::FasterLinearInterpolateImageFunction
< InputImageType > InterpolatorType
typedef std::vector
< MathScalarType > ListType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
short, 3 > MaskImageType
typedef double MathScalarType
typedef itk::Matrix
< MathScalarType, 3, 3 > Matrix3DType
typedef std::vector< unsigned int > MembershipType
typedef itk::SmartPointer< Self > Pointer
typedef MaskImageType::PointType PointType
typedef
BaseProbabilisticTractographyImageFilter Self
typedef itk::ProcessObject Superclass
typedef itk::Vector
< MathScalarType, 3 > Vector3DType
typedef
itk::VariableLengthVector
< MathScalarType > VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
void SetDesignMatrix ()
void SetEstimationMatrix ()
virtual void SetFAThreshold (double _arg)
void SetKappaPolynomialCoefficients (std::vector< double > &coefs)
virtual void SetOblateSigma (double _arg)
virtual void SetThresholdForProlateTensor (double _arg)
Public Member Functions inherited from anima::BaseProbabilisticTractographyImageFilter
void AddGradientDirection (unsigned int i, Vector3DType &grad)
void createVTKOutput (FiberProcessVectorType &filteredFibers, ListType &filteredWeights)
MathScalarType GetBValueItem (unsigned int i)
Vector3DType & GetDiffusionGradient (unsigned int i)
DirectionVectorType & GetDiffusionGradients ()
virtual InitialDirectionModeType GetInitialDirectionMode ()
InputImageType * GetInputImage (unsigned int i)
virtual double GetKappaOfPriorDistribution ()
virtual unsigned int GetModelDimension ()
vtkPolyData * GetOutput ()
void SetBValuesList (ListType bValuesList)
virtual void SetClusterDistance (unsigned int _arg)
virtual void SetComputeLocalColors (bool _arg)
virtual void SetCutMask (MaskImageType *_arg)
virtual void SetFiberTrashThreshold (double _arg)
virtual void SetFilterMask (MaskImageType *_arg)
virtual void SetForbiddenMask (MaskImageType *_arg)
void SetInitialColinearityDirection (const ColinearityDirectionType &colDir)
void SetInitialDirectionMode (const InitialDirectionModeType &dir)
void SetInputImagesFrom4DImage (Input4DImageType *in4DImage)
virtual void SetKappaOfPriorDistribution (double _arg)
virtual void SetKappaSplitThreshold (double _arg)
virtual void SetMAPMergeFibers (bool _arg)
virtual void SetMaxLengthFiber (double _arg)
virtual void SetMinimalNumberOfParticlesPerClass (unsigned int _arg)
virtual void SetMinLengthFiber (double _arg)
virtual void SetModelDimension (unsigned int _arg)
virtual void SetNumberOfFibersPerPixel (unsigned int _arg)
virtual void SetNumberOfParticles (unsigned int _arg)
void SetNumberOfThreads (unsigned int numThr)
virtual void SetPositionDistanceFuseThreshold (double _arg)
virtual void SetResamplingThreshold (double _arg)
virtual void SetSeedMask (MaskImageType *_arg)
virtual void SetStepProgression (double _arg)
void Update ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual bool CheckModelProperties (double estimatedB0Value, double estimatedNoiseValue, VectorType &modelValue, unsigned int threadId)
Check stopping criterions to stop a particle (model dependent, not implemented here)
virtual double ComputeLogWeightUpdate (double b0Value, double noiseValue, Vector3DType &newDirection, Vector3DType &sampling_direction, VectorType &modelValue, VectorType &dwiValue, double &log_prior, double &log_proposal, unsigned int threadId)
Update particle weight based on an underlying model and the chosen direction (model dependent, not implemented here)
virtual double ComputeModelEstimation (DWIInterpolatorPointerVectorType &dwiInterpolators, ContinuousIndexType &index, VectorType &dwiValue, double &noiseValue, VectorType &modelValue)
Estimate model from raw diffusion data (model dependent, not implemented here)
DTIProbabilisticTractographyImageFilter ()
void GetDTIMinorDirection (VectorType &modelValue, Vector3DType &resVec)
void GetDTIPrincipalDirection (const VectorType &modelValue, Vector3DType &resVec, bool is2d)
void GetEigenValueCombinations (VectorType &modelValue, double &meanLambda, double &perpLambda)
double GetFractionalAnisotropy (VectorType &modelValue)
double GetKappaFromFA (double FA)
double GetLinearCoefficient (VectorType &modelValue)
virtual Vector3DType InitializeFirstIterationFromModel (Vector3DType &colinearDir, VectorType &modelValue, unsigned int threadId)
Initialize first direction from user input (model dependent, not implemented here)
void PrepareTractography ()
Generate seed points.
virtual Vector3DType ProposeNewDirection (Vector3DType &oldDirection, VectorType &modelValue, Vector3DType &sampling_direction, double &log_prior, double &log_proposal, boost::mt19937 &random_generator, unsigned int threadId)
Propose new direction for a particle, given the old direction, and a model (model dependent, not implemented here)
virtual ~DTIProbabilisticTractographyImageFilter ()
Protected Member Functions inherited from anima::BaseProbabilisticTractographyImageFilter
BaseProbabilisticTractographyImageFilter ()
FiberProcessVectorType ComputeFiber (FiberType &fiber, DWIInterpolatorPointerVectorType &dwiInterpolators, unsigned int numThread, ListType &resultWeights)
This little guy is the one handling probabilistic tracking.
FiberProcessVectorType FilterOutputFibers (FiberProcessVectorType &fibers, ListType &weights)
Filter output fibers by ROIs and compute local colors.
bool MergeParticleClassFibers (FiberWorkType &fiberData, FiberProcessVectorType &outputMerged, unsigned int classNumber)
This guy takes the result of computefiber and merges the classes, each one becomes one fiber.
void ThreadTrack (unsigned int numThread, FiberProcessVectorType &resultFibers, ListType &resultWeights)
Doing the real tracking by calling ComputeFiber and merging its results.
unsigned int UpdateClassesMemberships (FiberWorkType &fiberData, DirectionVectorType &directions)
This ugly guy is the heart of multi-modal probabilistic tractography, making decisions on split and merges of particles.
virtual ~BaseProbabilisticTractographyImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::BaseProbabilisticTractographyImageFilter
static ITK_THREAD_RETURN_TYPE ThreadTracker (void *arg)
Multithread util function.
Detailed Description
Definition at line 12 of file animaDTIProbabilisticTractographyImageFilter.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::DTIProbabilisticTractographyImageFilter::ConstPointer
Definition at line 20 of file animaDTIProbabilisticTractographyImageFilter.h.
typedef vnl_matrix<double> anima::DTIProbabilisticTractographyImageFilter::MatrixFreeType
Definition at line 24 of file animaDTIProbabilisticTractographyImageFilter.h.
typedef itk::SmartPointer<Self> anima::DTIProbabilisticTractographyImageFilter::Pointer
Definition at line 19 of file animaDTIProbabilisticTractographyImageFilter.h.
typedef DTIProbabilisticTractographyImageFilter anima::DTIProbabilisticTractographyImageFilter::Self
SmartPointer typedef support
Definition at line 16 of file animaDTIProbabilisticTractographyImageFilter.h.
typedef BaseProbabilisticTractographyImageFilter anima::DTIProbabilisticTractographyImageFilter::Superclass
Definition at line 17 of file animaDTIProbabilisticTractographyImageFilter.h.
Constructor & Destructor Documentation
anima::DTIProbabilisticTractographyImageFilter::DTIProbabilisticTractographyImageFilter () protected
Definition at line 15 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::SetModelDimension().
anima::DTIProbabilisticTractographyImageFilter::~DTIProbabilisticTractographyImageFilter () protected virtual
Definition at line 26 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Member Function Documentation
bool anima::DTIProbabilisticTractographyImageFilter::CheckModelProperties (double estimatedB0Value, double estimatedNoiseValue, VectorType & modelValue, unsigned int threadId) protected virtual
Check stopping criterions to stop a particle (model dependent, not implemented here)
Implements anima::BaseProbabilisticTractographyImageFilter.
Definition at line 171 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References GetFractionalAnisotropy(), and anima::BaseProbabilisticTractographyImageFilter::GetModelDimension().
double anima::DTIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate (double b0Value, double noiseValue, Vector3DType & newDirection, Vector3DType & sampling_direction, VectorType & modelValue, VectorType & dwiValue, double & log_prior, double & log_proposal, unsigned int threadId) protected virtual
Update particle weight based on an underlying model and the chosen direction (model dependent, not implemented here)
Implements anima::BaseProbabilisticTractographyImageFilter.
Definition at line 196 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References anima::ComputeScalarProduct(), anima::BaseProbabilisticTractographyImageFilter::GetBValueItem(), anima::BaseProbabilisticTractographyImageFilter::GetDiffusionGradient(), anima::BaseProbabilisticTractographyImageFilter::GetDiffusionGradients(), GetDTIMinorDirection(), GetDTIPrincipalDirection(), GetEigenValueCombinations(), anima::BaseProbabilisticTractographyImageFilter::GetInputImage(), and GetLinearCoefficient().
double anima::DTIProbabilisticTractographyImageFilter::ComputeModelEstimation (DWIInterpolatorPointerVectorType & dwiInterpolators, ContinuousIndexType & index, VectorType & dwiValue, double & noiseValue, VectorType & modelValue) protected virtual
Estimate model from raw diffusion data (model dependent, not implemented here)
Implements anima::BaseProbabilisticTractographyImageFilter.
Definition at line 373 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::GetBValueItem(), anima::BaseProbabilisticTractographyImageFilter::GetModelDimension(), and anima::safe_log().
virtual::itk::LightObject::Pointer anima::DTIProbabilisticTractographyImageFilter::CreateAnother (void) const
void anima::DTIProbabilisticTractographyImageFilter::GetDTIMinorDirection (VectorType & modelValue, Vector3DType & resVec) protected
Definition at line 349 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Referenced by ComputeLogWeightUpdate().
void anima::DTIProbabilisticTractographyImageFilter::GetDTIPrincipalDirection (const VectorType & modelValue, Vector3DType & resVec, bool is2d) protected
Definition at line 319 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Referenced by ComputeLogWeightUpdate(), and ProposeNewDirection().
void anima::DTIProbabilisticTractographyImageFilter::GetEigenValueCombinations (VectorType & modelValue, double & meanLambda, double & perpLambda) protected
Definition at line 504 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Referenced by ComputeLogWeightUpdate().
double anima::DTIProbabilisticTractographyImageFilter::GetFractionalAnisotropy (VectorType & modelValue) protected
Definition at line 466 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Referenced by CheckModelProperties(), and ProposeNewDirection().
double anima::DTIProbabilisticTractographyImageFilter::GetKappaFromFA (double FA) protected
Definition at line 310 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Referenced by ProposeNewDirection().
double anima::DTIProbabilisticTractographyImageFilter::GetLinearCoefficient (VectorType & modelValue) protected
Definition at line 439 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Referenced by ComputeLogWeightUpdate(), and ProposeNewDirection().
virtual const char* anima::DTIProbabilisticTractographyImageFilter::GetNameOfClass () const virtual
Reimplemented from anima::BaseProbabilisticTractographyImageFilter.
DTIProbabilisticTractographyImageFilter::Vector3DType anima::DTIProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel (Vector3DType & colinearDir, VectorType & modelValue, unsigned int threadId) protected virtual
Initialize first direction from user input (model dependent, not implemented here)
Implements anima::BaseProbabilisticTractographyImageFilter.
Definition at line 99 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::Colinear, anima::ComputeScalarProduct(), anima::BaseProbabilisticTractographyImageFilter::GetInitialDirectionMode(), anima::BaseProbabilisticTractographyImageFilter::GetInputImage(), and anima::BaseProbabilisticTractographyImageFilter::Weight.
static Pointer anima::DTIProbabilisticTractographyImageFilter::New () static
void anima::DTIProbabilisticTractographyImageFilter::PrepareTractography () protected virtual
Generate seed points.
Reimplemented from anima::BaseProbabilisticTractographyImageFilter.
Definition at line 30 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::PrepareTractography(), SetDesignMatrix(), and SetEstimationMatrix().
DTIProbabilisticTractographyImageFilter::Vector3DType anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection (Vector3DType & oldDirection, VectorType & modelValue, Vector3DType & sampling_direction, double & log_prior, double & log_proposal, boost::mt19937 & random_generator, unsigned int threadId) protected virtual
Propose new direction for a particle, given the old direction, and a model (model dependent, not implemented here)
Implements anima::BaseProbabilisticTractographyImageFilter.
Definition at line 40 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References anima::ComputeScalarProduct(), anima::EvaluateWatsonPDF(), GetDTIPrincipalDirection(), GetFractionalAnisotropy(), anima::BaseProbabilisticTractographyImageFilter::GetInputImage(), GetKappaFromFA(), anima::BaseProbabilisticTractographyImageFilter::GetKappaOfPriorDistribution(), GetLinearCoefficient(), anima::safe_log(), and anima::SampleFromWatsonDistribution().
void anima::DTIProbabilisticTractographyImageFilter::SetDesignMatrix ()
Definition at line 268 of file animaDTIProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::GetBValueItem(), anima::BaseProbabilisticTractographyImageFilter::GetDiffusionGradient(), anima::BaseProbabilisticTractographyImageFilter::GetDiffusionGradients(), and anima::BaseProbabilisticTractographyImageFilter::GetModelDimension().
Referenced by PrepareTractography().
void anima::DTIProbabilisticTractographyImageFilter::SetEstimationMatrix ()
Definition at line 295 of file animaDTIProbabilisticTractographyImageFilter.cxx.
Referenced by PrepareTractography().
virtual void anima::DTIProbabilisticTractographyImageFilter::SetFAThreshold (double _arg) virtual
void anima::DTIProbabilisticTractographyImageFilter::SetKappaPolynomialCoefficients (std::vector< double > & coefs)
Definition at line 303 of file animaDTIProbabilisticTractographyImageFilter.cxx.
virtual void anima::DTIProbabilisticTractographyImageFilter::SetOblateSigma (double _arg) virtual
virtual void anima::DTIProbabilisticTractographyImageFilter::SetThresholdForProlateTensor (double _arg) virtual
The documentation for this class was generated from the following files:
animaDTIProbabilisticTractographyImageFilter.h
animaDTIProbabilisticTractographyImageFilter.cxx