ANIMA: anima::dtiTractographyImageFilter Class Reference
anima::dtiTractographyImageFilter Class Reference
#include <animaDTITractographyImageFilter.h>
Classes
struct trackerArguments
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::ContinuousIndex
< double, 3 > ContinuousIndexType
typedef
DTIInterpolatorType::Pointer DTIInterpolatorPointer
typedef
itk::LinearInterpolateImageFunction
< LogDTIImageType > DTIInterpolatorType
typedef std::vector< std::pair
< FiberProgressType, FiberType > > FiberProcessVectorType
enum FiberProgressType {
Forward,
Backward,
Both
}
typedef std::vector< PointType > FiberType
typedef MaskImageType::IndexType IndexType
typedef LogDTIImageType::Pointer LogDTIImagePointer
typedef itk::VectorImage
< float, 3 > LogDTIImageType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
short, 3 > MaskImageType
typedef itk::SmartPointer< Self > Pointer
typedef MaskImageType::PointType PointType
typedef dtiTractographyImageFilter Self
typedef itk::ProcessObject Superclass
typedef LogDTIImageType::PixelType VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void createVTKOutput (std::vector< std::vector< PointType > > &filteredFibers)
virtual const char * GetNameOfClass () const
vtkPolyData * GetOutput ()
void SetComputeLocalColors (bool flag)
void SetCutMask (MaskImageType *mask)
void SetForbiddenMask (MaskImageType *mask)
void SetInputImage (LogDTIImageType *input)
void SetMaxFiberAngle (double num)
void SetMaxLengthFiber (double num)
void SetMinLengthFiber (double num)
void SetNumberOfFibersPerPixel (unsigned int num)
void SetNumberOfThreads (unsigned int numThr)
void SetStepProgression (double num)
void SetStopFAThreshold (double num)
void SetTrackingMask (MaskImageType *mask)
void Update ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
FiberProcessVectorType ComputeFiber (FiberType &fiber, DTIInterpolatorType *dtiInterpolator, FiberProgressType ways)
dtiTractographyImageFilter ()
std::vector< FiberType > FilterOutputFibers (std::vector< FiberType > &fibers)
std::vector< double > GetDTIPrincipalDirection (VectorType &dtiLogValue, bool is2d)
double GetFA (VectorType &dtiLogValue)
void PrepareTractography ()
void ThreadTrack (unsigned int numThread, std::vector< FiberType > &resultFibers)
virtual ~dtiTractographyImageFilter ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadTracker (void *arg)
Detailed Description
Definition at line 18 of file animaDTITractographyImageFilter.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::dtiTractographyImageFilter::ConstPointer
Definition at line 26 of file animaDTITractographyImageFilter.h.
typedef itk::ContinuousIndex<double, 3> anima::dtiTractographyImageFilter::ContinuousIndexType
Definition at line 43 of file animaDTITractographyImageFilter.h.
typedef DTIInterpolatorType::Pointer anima::dtiTractographyImageFilter::DTIInterpolatorPointer
Definition at line 42 of file animaDTITractographyImageFilter.h.
typedef itk::LinearInterpolateImageFunction<LogDTIImageType> anima::dtiTractographyImageFilter::DTIInterpolatorType
Definition at line 41 of file animaDTITractographyImageFilter.h.
typedef std::vector<std::pair < FiberProgressType, FiberType > > anima::dtiTractographyImageFilter::FiberProcessVectorType
Definition at line 51 of file animaDTITractographyImageFilter.h.
typedef std::vector<PointType> anima::dtiTractographyImageFilter::FiberType
Definition at line 50 of file animaDTITractographyImageFilter.h.
typedef MaskImageType::IndexType anima::dtiTractographyImageFilter::IndexType
Definition at line 48 of file animaDTITractographyImageFilter.h.
typedef LogDTIImageType::Pointer anima::dtiTractographyImageFilter::LogDTIImagePointer
Definition at line 39 of file animaDTITractographyImageFilter.h.
typedef itk::VectorImage<float, 3> anima::dtiTractographyImageFilter::LogDTIImageType
Definition at line 38 of file animaDTITractographyImageFilter.h.
typedef MaskImageType::Pointer anima::dtiTractographyImageFilter::MaskImagePointer
Definition at line 46 of file animaDTITractographyImageFilter.h.
typedef itk::Image<unsigned short, 3> anima::dtiTractographyImageFilter::MaskImageType
Definition at line 45 of file animaDTITractographyImageFilter.h.
typedef itk::SmartPointer<Self> anima::dtiTractographyImageFilter::Pointer
Definition at line 25 of file animaDTITractographyImageFilter.h.
typedef MaskImageType::PointType anima::dtiTractographyImageFilter::PointType
Definition at line 47 of file animaDTITractographyImageFilter.h.
typedef dtiTractographyImageFilter anima::dtiTractographyImageFilter::Self
SmartPointer typedef support
Definition at line 22 of file animaDTITractographyImageFilter.h.
typedef itk::ProcessObject anima::dtiTractographyImageFilter::Superclass
Definition at line 23 of file animaDTITractographyImageFilter.h.
typedef LogDTIImageType::PixelType anima::dtiTractographyImageFilter::VectorType
Definition at line 40 of file animaDTITractographyImageFilter.h.
Member Enumeration Documentation
enum anima::dtiTractographyImageFilter::FiberProgressType
Enumerator
Forward
Backward
Both
Definition at line 32 of file animaDTITractographyImageFilter.h.
Constructor & Destructor Documentation
anima::dtiTractographyImageFilter::dtiTractographyImageFilter () protected
Definition at line 15 of file animaDTITractographyImageFilter.cxx.
anima::dtiTractographyImageFilter::~dtiTractographyImageFilter () protected virtual
Definition at line 29 of file animaDTITractographyImageFilter.cxx.
Member Function Documentation
dtiTractographyImageFilter::FiberProcessVectorType anima::dtiTractographyImageFilter::ComputeFiber (dtiTractographyImageFilter::FiberType & fiber, dtiTractographyImageFilter::DTIInterpolatorType * dtiInterpolator, dtiTractographyImageFilter::FiberProgressType ways) protected
Definition at line 298 of file animaDTITractographyImageFilter.cxx.
References Backward, Both, anima::ComputeOrientationAngle(), anima::ComputeScalarProduct(), Forward, GetDTIPrincipalDirection(), GetFA(), and anima::Revert().
Referenced by ThreadTrack().
virtual::itk::LightObject::Pointer anima::dtiTractographyImageFilter::CreateAnother (void) const
void anima::dtiTractographyImageFilter::createVTKOutput (std::vector< std::vector< PointType > > & filteredFibers)
Definition at line 238 of file animaDTITractographyImageFilter.cxx.
Referenced by Update().
std::vector< std::vector< dtiTractographyImageFilter::PointType > > anima::dtiTractographyImageFilter::FilterOutputFibers (std::vector< FiberType > & fibers) protected
Definition at line 187 of file animaDTITractographyImageFilter.cxx.
Referenced by Update().
std::vector< double > anima::dtiTractographyImageFilter::GetDTIPrincipalDirection (VectorType & dtiLogValue, bool is2d) protected
Definition at line 521 of file animaDTITractographyImageFilter.cxx.
Referenced by ComputeFiber().
double anima::dtiTractographyImageFilter::GetFA (VectorType & dtiLogValue) protected
Definition at line 480 of file animaDTITractographyImageFilter.cxx.
Referenced by ComputeFiber().
virtual const char* anima::dtiTractographyImageFilter::GetNameOfClass () const virtual
vtkPolyData* anima::dtiTractographyImageFilter::GetOutput () inline
Definition at line 77 of file animaDTITractographyImageFilter.h.
static Pointer anima::dtiTractographyImageFilter::New () static
void anima::dtiTractographyImageFilter::PrepareTractography () protected
Definition at line 64 of file animaDTITractographyImageFilter.cxx.
References Both.
Referenced by Update().
void anima::dtiTractographyImageFilter::SetComputeLocalColors (bool flag) inline
Definition at line 75 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetCutMask (MaskImageType * mask) inline
Definition at line 61 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetForbiddenMask (MaskImageType * mask) inline
Definition at line 60 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetInputImage (LogDTIImageType * input) inline
Definition at line 58 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetMaxFiberAngle (double num) inline
Definition at line 69 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetMaxLengthFiber (double num) inline
Definition at line 71 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetMinLengthFiber (double num) inline
Definition at line 70 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetNumberOfFibersPerPixel (unsigned int num) inline
Definition at line 64 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetNumberOfThreads (unsigned int numThr) inline
Definition at line 63 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetStepProgression (double num) inline
Definition at line 66 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetStopFAThreshold (double num) inline
Definition at line 67 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::SetTrackingMask (MaskImageType * mask) inline
Definition at line 59 of file animaDTITractographyImageFilter.h.
void anima::dtiTractographyImageFilter::ThreadTrack (unsigned int numThread, std::vector< FiberType > & resultFibers) protected
Definition at line 156 of file animaDTITractographyImageFilter.cxx.
References ComputeFiber().
Referenced by ThreadTracker().
ITK_THREAD_RETURN_TYPE anima::dtiTractographyImageFilter::ThreadTracker (void * arg) static protected
Definition at line 145 of file animaDTITractographyImageFilter.cxx.
References anima::dtiTractographyImageFilter::trackerArguments::resultFibersFromThreads, ThreadTrack(), and anima::dtiTractographyImageFilter::trackerArguments::trackerPtr.
Referenced by Update().
void anima::dtiTractographyImageFilter::Update ()
Definition at line 33 of file animaDTITractographyImageFilter.cxx.
References createVTKOutput(), FilterOutputFibers(), PrepareTractography(), anima::dtiTractographyImageFilter::trackerArguments::resultFibersFromThreads, ThreadTracker(), and anima::dtiTractographyImageFilter::trackerArguments::trackerPtr.
The documentation for this class was generated from the following files:
animaDTITractographyImageFilter.h
animaDTITractographyImageFilter.cxx