ANIMA: anima::SymmetricBMRegistrationMethod< TInputImageType > Class Template Reference
anima::SymmetricBMRegistrationMethod< TInputImageType > Class Template Reference
#include <animaSymmetricBMRegistrationMethod.h>
Public Types
typedef
Superclass::AffineTransformType AffineTransformType
typedef Superclass::AgregatorType AgregatorType
typedef
Superclass::BlockMatcherType BlockMatcherType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::InputImageType InputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
SymmetricBMRegistrationMethod Self
typedef
BaseBMRegistrationMethod
< TInputImageType > Superclass
typedef
Superclass::SVFTransformType SVFTransformType
typedef
Superclass::TransformPointer TransformPointer
Public Types inherited from anima::BaseBMRegistrationMethod< TInputImageType >
typedef
AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform
< typename
AgregatorType::ScalarType,
TInputImageType::ImageDimension > AffineTransformType
typedef AgregatorType::ScalarType AgregatorScalarType
typedef
anima::BaseTransformAgregator
< TInputImageType::ImageDimension > AgregatorType
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef
anima::BaseBlockMatcher
< TInputImageType > BlockMatcherType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef
DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef
rpi::DisplacementFieldTransform
< AgregatorScalarType,
TInputImageType::ImageDimension > DisplacementFieldTransformType
typedef
TInputImageType::IOPixelType ImageScalarType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImageType InputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
ResamplerFilterType::Pointer ResamplerFilterPointer
typedef
itk::ImageToImageFilter
< InputImageType,
InputImageType > ResamplerFilterType
typedef BaseBMRegistrationMethod Self
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef
itk::StationaryVelocityFieldTransform
< AgregatorScalarType,
TInputImageType::ImageDimension > SVFTransformType
typedef
TransformOutputType::Pointer TransformOutputPointer
typedef
itk::DataObjectDecorator
< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef
AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
void SetReverseBlockMatcher (BlockMatcherType *matcher)
Public Member Functions inherited from anima::BaseBMRegistrationMethod< TInputImageType >
void Abort ()
virtual AgregatorType * GetAgregator ()
BlockMatcherType * GetBlockMatcher ()
virtual InputImageType * GetFixedImage ()
TransformPointer & GetInitialTransform ()
virtual const unsigned int & GetMaximumIterations () const
virtual const double & GetMinimalTransformError () const
virtual InputImageType * GetMovingImage ()
ResamplerFilterPointer & GetMovingImageResampler ()
TransformOutputType * GetOutput ()
ResamplerFilterPointer & GetReferenceImageResampler ()
virtual const double & GetSVFElasticRegSigma () const
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx)
virtual void SetAgregator (AgregatorType *_arg)
void SetBlockMatcher (BlockMatcherType *matcher)
virtual void SetFixedImage (InputImageType *_arg)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMinimalTransformError (double _arg)
virtual void SetMovingImage (InputImageType *_arg)
void SetMovingImageResampler (ResamplerFilterType *filter)
void SetReferenceImageResampler (ResamplerFilterType *filter)
virtual void SetSVFElasticRegSigma (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn)
SymmetricBMRegistrationMethod ()
virtual ~SymmetricBMRegistrationMethod ()
Protected Member Functions inherited from anima::BaseBMRegistrationMethod< TInputImageType >
BaseBMRegistrationMethod ()
virtual bool ComposeAddOnWithTransform (TransformPointer &computedTransform, TransformType *addOn)
void GenerateData ()
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const
virtual void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &movingImage)
virtual void SetupTransform (TransformPointer &optimizedTransform)
void StartOptimization ()
virtual ~BaseBMRegistrationMethod ()
Detailed Description
template<typename TInputImageType>
class anima::SymmetricBMRegistrationMethod< TInputImageType >
Definition at line 8 of file animaSymmetricBMRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImageType > typedef Superclass::AffineTransformType anima::SymmetricBMRegistrationMethod< TInputImageType >::AffineTransformType
Definition at line 21 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::AgregatorType anima::SymmetricBMRegistrationMethod< TInputImageType >::AgregatorType
Definition at line 20 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::BlockMatcherType anima::SymmetricBMRegistrationMethod< TInputImageType >::BlockMatcherType
Definition at line 19 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef itk::SmartPointer<const Self> anima::SymmetricBMRegistrationMethod< TInputImageType >::ConstPointer
Definition at line 15 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::InputImageType anima::SymmetricBMRegistrationMethod< TInputImageType >::InputImageType
Definition at line 17 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef itk::SmartPointer<Self> anima::SymmetricBMRegistrationMethod< TInputImageType >::Pointer
Definition at line 14 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef SymmetricBMRegistrationMethod anima::SymmetricBMRegistrationMethod< TInputImageType >::Self
Standard class typedefs.
Definition at line 12 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef BaseBMRegistrationMethod<TInputImageType> anima::SymmetricBMRegistrationMethod< TInputImageType >::Superclass
Definition at line 13 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::SVFTransformType anima::SymmetricBMRegistrationMethod< TInputImageType >::SVFTransformType
Definition at line 22 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::TransformPointer anima::SymmetricBMRegistrationMethod< TInputImageType >::TransformPointer
Definition at line 18 of file animaSymmetricBMRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImageType > anima::SymmetricBMRegistrationMethod< TInputImageType >::SymmetricBMRegistrationMethod () inline protected
Definition at line 32 of file animaSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > virtual anima::SymmetricBMRegistrationMethod< TInputImageType >::~SymmetricBMRegistrationMethod () inline protected virtual
Definition at line 33 of file animaSymmetricBMRegistrationMethod.h.
Member Function Documentation
template<typename TInputImageType > virtual::itk::LightObject::Pointer anima::SymmetricBMRegistrationMethod< TInputImageType >::CreateAnother (void) const
template<typename TInputImageType > virtual const char* anima::SymmetricBMRegistrationMethod< TInputImageType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
template<typename TInputImageType > static Pointer anima::SymmetricBMRegistrationMethod< TInputImageType >::New () static
template<typename TInputImageType > void anima::SymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) protected virtual
Implements anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 13 of file animaSymmetricBMRegistrationMethod.hxx.
References anima::GetExponential(), anima::GetLogarithm(), anima::DenseSVFTransformAgregator< NDimensions >::SetDamIndexes(), and anima::BalooSVFTransformAgregator< NDimensions >::SetDamIndexes().
template<typename TInputImageType > void anima::SymmetricBMRegistrationMethod< TInputImageType >::SetReverseBlockMatcher (BlockMatcherType * matcher) inline
Definition at line 29 of file animaSymmetricBMRegistrationMethod.h.
The documentation for this class was generated from the following files:
animaSymmetricBMRegistrationMethod.h
animaSymmetricBMRegistrationMethod.hxx