ANIMA: anima::FibersWriter Class Reference
anima::FibersWriter Class Reference
#include <animaFibersWriter.h>
Public Member Functions
FibersWriter ()
void SetFileName (std::string &name)
void SetInputData (vtkPolyData *data)
void Update ()
~FibersWriter ()
Protected Member Functions
void WriteFileAsMedinriaFibers ()
void WriteFileAsVTKAscii ()
void WriteFileAsVTKXML ()
Detailed Description
Definition at line 11 of file animaFibersWriter.h.
Constructor & Destructor Documentation
anima::FibersWriter::FibersWriter () inline
Definition at line 14 of file animaFibersWriter.h.
anima::FibersWriter::~FibersWriter () inline
Definition at line 20 of file animaFibersWriter.h.
Member Function Documentation
void anima::FibersWriter::SetFileName (std::string & name) inline
Definition at line 23 of file animaFibersWriter.h.
Referenced by main().
void anima::FibersWriter::SetInputData (vtkPolyData * data) inline
Definition at line 22 of file animaFibersWriter.h.
Referenced by main().
void anima::FibersWriter::Update ()
Definition at line 13 of file animaFibersWriter.cxx.
References WriteFileAsMedinriaFibers(), WriteFileAsVTKAscii(), and WriteFileAsVTKXML().
Referenced by main().
void anima::FibersWriter::WriteFileAsMedinriaFibers () protected
Definition at line 49 of file animaFibersWriter.cxx.
Referenced by Update().
void anima::FibersWriter::WriteFileAsVTKAscii () protected
Definition at line 30 of file animaFibersWriter.cxx.
Referenced by Update().
void anima::FibersWriter::WriteFileAsVTKXML () protected
Definition at line 38 of file animaFibersWriter.cxx.
Referenced by Update().
The documentation for this class was generated from the following files:
animaFibersWriter.h
animaFibersWriter.cxx