ANIMA: anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType > Class Template Reference
anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType > Class Template Reference abstract
#include <animaOrientedModelBaseResampleImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef TOutputImage::DirectionType DirectionType
typedef GeometryImageType::Pointer GeometryImagePointer
typedef itk::Image< unsigned
char, itkGetStaticConstMacro(ImageDimension)> GeometryImageType
typedef InputImageType::Pointer InputImagePointer
typedef itk::VectorImage
< TInputScalarType, Dimension > InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::PixelType InputPixelType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
itk::InterpolateImageFunction
< InputImageType,
TInterpolatorPrecisionType > InterpolatorType
typedef
itk::MatrixOffsetTransformBase
< TInterpolatorPrecisionType,
itkGetStaticConstMacro(ImageDimension),
itkGetStaticConstMacro(ImageDimension)> MatrixTransformType
typedef TOutputImage::PointType OriginPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef TOutputImage::RegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef InterpolatorType::PointType PointType
typedef TOutputImage::RegionType RegionType
typedef
OrientedModelBaseResampleImageFilter Self
typedef TOutputImage::SpacingType SpacingType
typedef
itk::ImageToImageFilter
< TInputImage, TOutputImage > Superclass
typedef itk::VectorImage
< TInputScalarType,
itkGetStaticConstMacro(ImageDimension)> TInputImage
typedef itk::VectorImage
< TInputScalarType,
itkGetStaticConstMacro(ImageDimension)> TOutputImage
typedef TransformType::Pointer TransformPointer
typedef itk::Transform
< TInterpolatorPrecisionType,
itkGetStaticConstMacro(ImageDimension),
itkGetStaticConstMacro(ImageDimension)> TransformType
Public Member Functions
virtual InterpolatorType * GetInterpolator ()
virtual const char * GetNameOfClass () const
virtual const DirectionType & GetOutputDirection () const
virtual const RegionType & GetOutputLargestPossibleRegion () const
virtual const OriginPointType & GetOutputOrigin () const
virtual const SpacingType & GetOutputSpacing () const
virtual TransformType * GetTransform ()
virtual void SetInterpolator (InterpolatorPointer _arg)
virtual void SetOutputDirection (DirectionType _arg)
virtual void SetOutputLargestPossibleRegion (RegionType _arg)
virtual void SetOutputOrigin (OriginPointType _arg)
virtual void SetOutputSpacing (SpacingType _arg)
void SetTransform (TransformType *trsf)
Static Public Attributes
static const unsigned int ImageDimension = InputImageType::ImageDimension
Protected Member Functions
virtual void BeforeThreadedGenerateData (void)
vnl_matrix< double > ComputeLinearRotationMatrix ()
void ComputeLocalRotationMatrix (InputIndexType &index, vnl_matrix< double > &rotMatrix)
virtual void ComputeRotationParametersFromRotationMatrix (const vnl_matrix< double > &transformRotationMatrix, vnl_matrix< double > &modelRotationMatrix)
For some models, the transform induced rotation matrix is not enough and needs to be used to get rotation parameters, default is just a copy of the current matrix.
virtual unsigned int GetOutputVectorLength ()
virtual void InitializeInterpolator ()
Initializes the default interpolator, might change in derived classes.
bool isZero (const InputPixelType &dataVec)
void LinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
void NonLinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
OrientedModelBaseResampleImageFilter ()
void PrintSelf (std::ostream &os, itk::Indent indent) const
virtual void RotateInterpolatedModel (const InputPixelType &interpolatedModel, vnl_matrix< double > &modelRotationMatrix, InputPixelType &rotatedModel)=0
Needs to be implemented in sub-classes, does the actual rotation of the model.
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
virtual ~OrientedModelBaseResampleImageFilter ()
Detailed Description
template<typename TInputScalarType, unsigned int Dimension, typename TInterpolatorPrecisionType = float>
class anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >
Definition at line 14 of file animaOrientedModelBaseResampleImageFilter.h.
Member Typedef Documentation
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<const Self> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ConstPointer
Definition at line 31 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef InterpolatorType::ContinuousIndexType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ContinuousIndexType
Definition at line 36 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef TOutputImage::DirectionType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::DirectionType
Definition at line 76 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef GeometryImageType::Pointer anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GeometryImagePointer
Definition at line 27 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::Image<unsigned char, itkGetStaticConstMacro(ImageDimension)> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GeometryImageType
Definition at line 26 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef InputImageType::Pointer anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::InputImagePointer
Image typedef support
Definition at line 46 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::VectorImage<TInputScalarType, Dimension> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::InputImageType
Definition at line 20 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef InputImageType::IndexType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::InputIndexType
Definition at line 43 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef InputImageType::PixelType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::InputPixelType
Definition at line 40 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef InterpolatorType::Pointer anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::InterpolatorPointer
Definition at line 34 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::InterpolateImageFunction<InputImageType, TInterpolatorPrecisionType> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::InterpolatorType
Definition at line 33 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::MatrixOffsetTransformBase<TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::MatrixTransformType
Definition at line 56 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef TOutputImage::PointType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::OriginPointType
Definition at line 75 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef TOutputImage::Pointer anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::OutputImagePointer
Definition at line 47 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef TOutputImage::RegionType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::OutputImageRegionType
Definition at line 48 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<Self> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::Pointer
Definition at line 30 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef InterpolatorType::PointType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::PointType
Definition at line 37 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef TOutputImage::RegionType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::RegionType
Definition at line 77 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef OrientedModelBaseResampleImageFilter anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::Self
Standard class typedefs.
Definition at line 19 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef TOutputImage::SpacingType anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::SpacingType
Definition at line 72 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::Superclass
Definition at line 29 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::VectorImage<TInputScalarType, itkGetStaticConstMacro(ImageDimension)> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::TInputImage
Definition at line 23 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::VectorImage<TInputScalarType, itkGetStaticConstMacro(ImageDimension)> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::TOutputImage
Definition at line 24 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef TransformType::Pointer anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::TransformPointer
Definition at line 58 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> typedef itk::Transform<TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::TransformType
Definition at line 52 of file animaOrientedModelBaseResampleImageFilter.h.
Constructor & Destructor Documentation
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::OrientedModelBaseResampleImageFilter () inline protected
Definition at line 92 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::~OrientedModelBaseResampleImageFilter () inline protected virtual
Definition at line 100 of file animaOrientedModelBaseResampleImageFilter.h.
Member Function Documentation
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::BeforeThreadedGenerateData (void) protected virtual
Reimplemented in anima::FiniteStrainODFResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >.
Definition at line 37 of file animaOrientedModelBaseResampleImageFilter.hxx.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > vnl_matrix< double > anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ComputeLinearRotationMatrix () protected
Definition at line 178 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::ExtractRotationFromMatrixTransform().
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ComputeLocalRotationMatrix (InputIndexType & index, vnl_matrix< double > & rotMatrix) protected
Definition at line 192 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::RecomposeTensor().
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ComputeRotationParametersFromRotationMatrix (const vnl_matrix< double > & transformRotationMatrix, vnl_matrix< double > & modelRotationMatrix) inline protected virtual
For some models, the transform induced rotation matrix is not enough and needs to be used to get rotation parameters, default is just a copy of the current matrix.
Definition at line 135 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual InterpolatorType* anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetInterpolator () virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual const char* anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented in anima::FiniteStrainTensorResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >, and anima::FiniteStrainODFResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual const DirectionType& anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetOutputDirection () const virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual const RegionType& anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetOutputLargestPossibleRegion () const virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual const OriginPointType& anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetOutputOrigin () const virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual const SpacingType& anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetOutputSpacing () const virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > unsigned int anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetOutputVectorLength () protected virtual
Definition at line 26 of file animaOrientedModelBaseResampleImageFilter.hxx.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual TransformType* anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::GetTransform () virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::InitializeInterpolator () protected virtual
Initializes the default interpolator, might change in derived classes.
Definition at line 15 of file animaOrientedModelBaseResampleImageFilter.hxx.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> bool anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::isZero (const InputPixelType & dataVec) inline protected
Definition at line 107 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::LinearThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 80 of file animaOrientedModelBaseResampleImageFilter.hxx.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::NonLinearThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 132 of file animaOrientedModelBaseResampleImageFilter.hxx.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::PrintSelf (std::ostream & os, itk::Indent indent) const inline protected
Definition at line 120 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::RotateInterpolatedModel (const InputPixelType & interpolatedModel, vnl_matrix< double > & modelRotationMatrix, InputPixelType & rotatedModel) protected pure virtual
Needs to be implemented in sub-classes, does the actual rotation of the model.
Implemented in anima::FiniteStrainODFResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >, and anima::FiniteStrainTensorResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::SetInterpolator (InterpolatorPointer _arg) virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::SetOutputDirection (DirectionType _arg) virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::SetOutputLargestPossibleRegion (RegionType _arg) virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::SetOutputOrigin (OriginPointType _arg) virtual
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelVectorImage().
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::SetOutputSpacing (SpacingType _arg) virtual
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::SetTransform (TransformType * trsf) inline
Definition at line 60 of file animaOrientedModelBaseResampleImageFilter.h.
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 69 of file animaOrientedModelBaseResampleImageFilter.hxx.
Member Data Documentation
template<typename TInputScalarType , unsigned int Dimension, typename TInterpolatorPrecisionType = float> const unsigned int anima::OrientedModelBaseResampleImageFilter< TInputScalarType, Dimension, TInterpolatorPrecisionType >::ImageDimension = InputImageType::ImageDimension static
Definition at line 21 of file animaOrientedModelBaseResampleImageFilter.h.
The documentation for this class was generated from the following files:
animaOrientedModelBaseResampleImageFilter.h
animaOrientedModelBaseResampleImageFilter.hxx