ANIMA: anima::RandomInitializer Class Reference
anima::RandomInitializer Class Reference
Class initializing ramdomly a gaussian model.
#include <animaRandomInitializer.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
itk::Statistics::GaussianMembershipFunction
< MeasurementVectorType > GaussianFunctionType
typedef
itk::VariableLengthVector
< double > MeasurementVectorType
typedef itk::SmartPointer< Self > Pointer
typedef RandomInitializer Self
typedef itk::ProcessObject Superclass
Public Types inherited from anima::ModelInitializer
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
itk::Statistics::GaussianMembershipFunction
< MeasurementVectorType > GaussianFunctionType
typedef
itk::VariableLengthVector
< double > MeasurementVectorType
typedef itk::SmartPointer< Self > Pointer
typedef ModelInitializer Self
typedef itk::ProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual unsigned int GetDimensionGaussian ()
virtual const char * GetNameOfClass () const
virtual unsigned int GetNbGaussian ()
virtual void SetDimensionGaussian (unsigned int _arg)
void SetMaxValues (std::vector< double > &max)
Set max values of random means.
void SetMinValues (std::vector< double > &min)
Set min values of random means.
virtual void SetNbGaussian (unsigned int _arg)
void Update ()
Public Member Functions inherited from anima::ModelInitializer
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< double > GetAlphas ()
std::vector
< GaussianFunctionType::Pointer > GetInitialization ()
returns a new initialization for the model
virtual bool GetVerbose ()
virtual void SetVerbose (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::ModelInitializer
static Pointer New ()
Protected Member Functions
void operator= (const Self &)
itk::Statistics::GaussianMembershipFunction
< itk::VariableLengthVector
< double > >::Pointer randomDistribution ()
initilize a Gaussian distribution
RandomInitializer (const Self &)
RandomInitializer ()
double randUniform (double min, double max)
virtual ~RandomInitializer ()
Protected Member Functions inherited from anima::ModelInitializer
ModelInitializer (const Self &)
ModelInitializer ()
void operator= (const Self &)
virtual ~ModelInitializer ()
Protected Attributes
unsigned int m_DimensionGaussian
unsigned int m_NbGaussian
std::vector< double > maxValues
max values
std::vector< double > minValues
min values
Protected Attributes inherited from anima::ModelInitializer
std::vector< double > m_Alphas
std::vector
< GaussianFunctionType::Pointer > m_GaussianModel
bool m_Verbose
Detailed Description
Class initializing ramdomly a gaussian model.
Definition at line 13 of file animaRandomInitializer.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::RandomInitializer::ConstPointer
Definition at line 21 of file animaRandomInitializer.h.
typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > anima::RandomInitializer::GaussianFunctionType
Definition at line 30 of file animaRandomInitializer.h.
typedef itk::VariableLengthVector<double> anima::RandomInitializer::MeasurementVectorType
Definition at line 27 of file animaRandomInitializer.h.
typedef itk::SmartPointer<Self> anima::RandomInitializer::Pointer
Definition at line 20 of file animaRandomInitializer.h.
typedef RandomInitializer anima::RandomInitializer::Self
Standard class typedefs.
Definition at line 18 of file animaRandomInitializer.h.
typedef itk::ProcessObject anima::RandomInitializer::Superclass
Definition at line 19 of file animaRandomInitializer.h.
Constructor & Destructor Documentation
anima::RandomInitializer::RandomInitializer (const Self &) protected
anima::RandomInitializer::RandomInitializer () inline protected
Definition at line 53 of file animaRandomInitializer.h.
virtual anima::RandomInitializer::~RandomInitializer () inline protected virtual
Definition at line 61 of file animaRandomInitializer.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::RandomInitializer::CreateAnother (void) const
virtual unsigned int anima::RandomInitializer::GetDimensionGaussian () virtual
virtual const char* anima::RandomInitializer::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::ModelInitializer.
virtual unsigned int anima::RandomInitializer::GetNbGaussian () virtual
static Pointer anima::RandomInitializer::New () static
Method for creation through the object factory.
Referenced by anima::HierarchicalInitializer< TInputImage, TMaskImage >::ComputeSolution1D().
void anima::RandomInitializer::operator= (const Self &) protected
itk::Statistics::GaussianMembershipFunction< itk::VariableLengthVector< double > >::Pointer anima::RandomInitializer::randomDistribution () protected
initilize a Gaussian distribution
Definition at line 55 of file animaRandomInitializer.cxx.
References m_DimensionGaussian, maxValues, minValues, and randUniform().
Referenced by Update().
double anima::RandomInitializer::randUniform (double min, double max) protected
Definition at line 76 of file animaRandomInitializer.cxx.
Referenced by randomDistribution().
virtual void anima::RandomInitializer::SetDimensionGaussian (unsigned int _arg) virtual
void anima::RandomInitializer::SetMaxValues (std::vector< double > & max) inline
Set max values of random means.
Definition at line 40 of file animaRandomInitializer.h.
void anima::RandomInitializer::SetMinValues (std::vector< double > & min) inline
Set min values of random means.
Definition at line 36 of file animaRandomInitializer.h.
virtual void anima::RandomInitializer::SetNbGaussian (unsigned int _arg) virtual
void anima::RandomInitializer::Update ()
Definition at line 6 of file animaRandomInitializer.cxx.
References anima::ModelInitializer::m_Alphas, m_DimensionGaussian, anima::ModelInitializer::m_GaussianModel, m_NbGaussian, maxValues, minValues, and randomDistribution().
Member Data Documentation
unsigned int anima::RandomInitializer::m_DimensionGaussian protected
Definition at line 80 of file animaRandomInitializer.h.
Referenced by randomDistribution(), and Update().
unsigned int anima::RandomInitializer::m_NbGaussian protected
Definition at line 79 of file animaRandomInitializer.h.
Referenced by Update().
std::vector<double> anima::RandomInitializer::maxValues protected
max values
Definition at line 77 of file animaRandomInitializer.h.
Referenced by randomDistribution(), and Update().
std::vector<double> anima::RandomInitializer::minValues protected
min values
Definition at line 73 of file animaRandomInitializer.h.
Referenced by randomDistribution(), and Update().
The documentation for this class was generated from the following files:
animaRandomInitializer.h
animaRandomInitializer.cxx