ANIMA: anima::LowMemoryLocalPatchMeanDistanceBridge Class Reference
anima::LowMemoryLocalPatchMeanDistanceBridge Class Reference
#include <animaLowMemLocalPatchMeanDistanceBridge.h>
Public Types
typedef
anima::ImageDataSplitter
< InputImageType > ImageSplitterType
typedef
LocalPatchMeanDistanceImageFilter
< double >::InputImageType InputImageType
typedef
anima::LocalPatchMeanDistanceImageFilter
< double > MainFilterType
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef
LocalPatchMeanDistanceImageFilter
< double >
::OutputImageRegionType OutputImageRegionType
typedef
LocalPatchMeanDistanceImageFilter
< double >::OutputImageType OutputImageType
Public Member Functions
void BuildAndWrite (OutputImageType *tmpIm, std::string resName, OutputImageType::RegionType finalROI)
std::string GetNameOfClass ()
LowMemoryLocalPatchMeanDistanceBridge ()
void SetComputationMask (std::string &cMask)
void SetDatabaseNames (std::string &fileList)
void SetNbSplits (unsigned int nbSplits)
void SetNumberOfThreads (unsigned int nbT)
void SetOutputMeanName (std::string &pref)
void SetOutputStdName (std::string &pref)
void SetPatchHalfSize (unsigned int patchHalf)
void Update (int specificSplitToDo=-1, bool genOutputDescriptionData=false)
~LowMemoryLocalPatchMeanDistanceBridge ()
Detailed Description
Definition at line 9 of file animaLowMemLocalPatchMeanDistanceBridge.h.
Member Typedef Documentation
typedef anima::ImageDataSplitter< InputImageType > anima::LowMemoryLocalPatchMeanDistanceBridge::ImageSplitterType
Definition at line 16 of file animaLowMemLocalPatchMeanDistanceBridge.h.
typedef LocalPatchMeanDistanceImageFilter<double>::InputImageType anima::LowMemoryLocalPatchMeanDistanceBridge::InputImageType
Definition at line 12 of file animaLowMemLocalPatchMeanDistanceBridge.h.
typedef anima::LocalPatchMeanDistanceImageFilter<double> anima::LowMemoryLocalPatchMeanDistanceBridge::MainFilterType
Definition at line 17 of file animaLowMemLocalPatchMeanDistanceBridge.h.
typedef itk::Image<unsigned char,3> anima::LowMemoryLocalPatchMeanDistanceBridge::MaskImageType
Definition at line 18 of file animaLowMemLocalPatchMeanDistanceBridge.h.
typedef LocalPatchMeanDistanceImageFilter<double>::OutputImageRegionType anima::LowMemoryLocalPatchMeanDistanceBridge::OutputImageRegionType
Definition at line 14 of file animaLowMemLocalPatchMeanDistanceBridge.h.
typedef LocalPatchMeanDistanceImageFilter<double>::OutputImageType anima::LowMemoryLocalPatchMeanDistanceBridge::OutputImageType
Definition at line 13 of file animaLowMemLocalPatchMeanDistanceBridge.h.
Constructor & Destructor Documentation
anima::LowMemoryLocalPatchMeanDistanceBridge::LowMemoryLocalPatchMeanDistanceBridge ()
Definition at line 8 of file animaLowMemLocalPatchMeanDistanceBridge.cxx.
anima::LowMemoryLocalPatchMeanDistanceBridge::~LowMemoryLocalPatchMeanDistanceBridge ()
Definition at line 19 of file animaLowMemLocalPatchMeanDistanceBridge.cxx.
Member Function Documentation
void anima::LowMemoryLocalPatchMeanDistanceBridge::BuildAndWrite (OutputImageType * tmpIm, std::string resName, OutputImageType::RegionType finalROI)
Definition at line 172 of file animaLowMemLocalPatchMeanDistanceBridge.cxx.
Referenced by Update().
std::string anima::LowMemoryLocalPatchMeanDistanceBridge::GetNameOfClass () inline
Definition at line 23 of file animaLowMemLocalPatchMeanDistanceBridge.h.
void anima::LowMemoryLocalPatchMeanDistanceBridge::SetComputationMask (std::string & cMask)
Definition at line 25 of file animaLowMemLocalPatchMeanDistanceBridge.cxx.
References anima::ImageDataSplitter< TInputImage >::SetComputationMask().
Referenced by main().
void anima::LowMemoryLocalPatchMeanDistanceBridge::SetDatabaseNames (std::string & fileList) inline
Definition at line 27 of file animaLowMemLocalPatchMeanDistanceBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetFileNames().
void anima::LowMemoryLocalPatchMeanDistanceBridge::SetNbSplits (unsigned int nbSplits) inline
Definition at line 35 of file animaLowMemLocalPatchMeanDistanceBridge.h.
void anima::LowMemoryLocalPatchMeanDistanceBridge::SetNumberOfThreads (unsigned int nbT) inline
Definition at line 36 of file animaLowMemLocalPatchMeanDistanceBridge.h.
void anima::LowMemoryLocalPatchMeanDistanceBridge::SetOutputMeanName (std::string & pref) inline
Definition at line 32 of file animaLowMemLocalPatchMeanDistanceBridge.h.
void anima::LowMemoryLocalPatchMeanDistanceBridge::SetOutputStdName (std::string & pref) inline
Definition at line 33 of file animaLowMemLocalPatchMeanDistanceBridge.h.
void anima::LowMemoryLocalPatchMeanDistanceBridge::SetPatchHalfSize (unsigned int patchHalf) inline
Definition at line 38 of file animaLowMemLocalPatchMeanDistanceBridge.h.
void anima::LowMemoryLocalPatchMeanDistanceBridge::Update (int specificSplitToDo = -1, bool genOutputDescriptionData = false)
Definition at line 36 of file animaLowMemLocalPatchMeanDistanceBridge.cxx.
References BuildAndWrite(), anima::ImageDataSplitter< TInputImage >::EmptyMask(), anima::ImageDataSplitter< TInputImage >::GetBlockRegionInsideMargin(), anima::ImageDataSplitter< TInputImage >::GetNbImages(), anima::ImageDataSplitter< TInputImage >::GetOutput(), anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin(), anima::ImageDataSplitter< TInputImage >::GetSpecificBlockRegion(), anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::New(), anima::ImageDataSplitter< TInputImage >::SetBlockIndex(), anima::ImageDataSplitter< TInputImage >::SetBlockMargin(), anima::ImageDataSplitter< TInputImage >::SetNumberOfBlocks(), and anima::ImageDataSplitter< TInputImage >::Update().
The documentation for this class was generated from the following files:
animaLowMemLocalPatchMeanDistanceBridge.h
animaLowMemLocalPatchMeanDistanceBridge.cxx