ANIMA: anima::BalooSVFTransformAgregator< NDimensions > Class Template Reference
anima::BalooSVFTransformAgregator< NDimensions > Class Template Reference
#include <animaBalooSVFTransformAgregator.h>
Public Types
typedef
Superclass::BaseInputTransformType BaseInputTransformType
typedef
itk::MatrixOffsetTransformBase
< InternalScalarType,
NDimensions, NDimensions > BaseMatrixTransformType
typedef
itk::StationaryVelocityFieldTransform
< ScalarType, NDimensions > BaseOutputTransformType
typedef WeightImageType::IndexType IndexType
typedef
Superclass::InternalScalarType InternalScalarType
typedef
BaseMatrixTransformType::ParametersType ParametersType
typedef Superclass::PointType PointType
typedef Superclass::ScalarType ScalarType
typedef BaseTransformAgregator
< NDimensions > Superclass
typedef
VelocityFieldType::DirectionType VelocityFieldDirectionType
typedef
VelocityFieldType::IndexType VelocityFieldIndexType
typedef
VelocityFieldType::PixelType VelocityFieldPixelType
typedef VelocityFieldType::Pointer VelocityFieldPointer
typedef
VelocityFieldType::PointType VelocityFieldPointType
typedef
VelocityFieldType::RegionType VelocityFieldRegionType
typedef
VelocityFieldType::SpacingType VelocityFieldSpacingType
typedef
BaseOutputTransformType::VectorFieldType VelocityFieldType
typedef WeightImageType::Pointer WeightImagePointer
typedef itk::Image< ScalarType,
NDimensions > WeightImageType
Public Types inherited from anima::BaseTransformAgregator< NDimensions >
typedef
BaseInputTransformType::Pointer BaseInputTransformPointer
typedef itk::Transform
< InternalScalarType,
NDimensions, NDimensions > BaseInputTransformType
typedef itk::Transform
< ScalarType, NDimensions,
NDimensions > BaseOutputTransformType
typedef double InternalScalarType
typedef itk::Point
< InternalScalarType,
NDimensions > PointType
typedef itk::ImageRegion
< NDimensions > RegionType
typedef double ScalarType
enum TRANSFORM_TYPE {
TRANSLATION,
RIGID,
AFFINE,
SVF
}
Public Member Functions
BalooSVFTransformAgregator ()
double GetExtrapolationSigma ()
unsigned int GetNumberOfThreads ()
double GetOutlierRejectionSigma ()
void SetDamIndexes (std::vector< IndexType > &indexes)
void SetExtrapolationSigma (double sigma)
template<class TInputImageType >
void SetGeometryInformation (const TInputImageType *geomImage)
void SetNumberOfThreads (unsigned int num)
void SetOutlierRejectionSigma (double sigma)
virtual bool Update ()
virtual ~BalooSVFTransformAgregator ()
Public Member Functions inherited from anima::BaseTransformAgregator< NDimensions >
BaseTransformAgregator ()
PointType & GetInputOrigin (unsigned int i)
std::vector< PointType > & GetInputOrigins ()
std::vector< RegionType > & GetInputRegions ()
BaseInputTransformType * GetInputTransform (unsigned int i)
std::vector
< BaseInputTransformPointer > & GetInputTransforms ()
TRANSFORM_TYPE GetInputTransformType ()
InternalScalarType GetInputWeight (unsigned int i)
std::vector< InternalScalarType > & GetInputWeights ()
BaseOutputTransformType * GetOutput ()
TRANSFORM_TYPE GetOutputTransformType ()
void SetInputOrigins (const std::vector< PointType > &inputOrigins)
template<class TInputImageType >
void SetInputRegions (const TInputImageType *refImage, const std::vector< RegionType > &inputRegions)
void SetInputTransforms (std::vector< BaseInputTransformPointer > &inputTransforms)
void SetInputTransformType (TRANSFORM_TYPE name)
void SetInputWeight (unsigned int i, double w)
void SetInputWeights (const std::vector< InternalScalarType > &weights)
void SetOutputTransformType (TRANSFORM_TYPE name)
void SetUpToDate (bool value)
virtual ~BaseTransformAgregator ()
Protected Attributes
std::vector< IndexType > m_DamIndexes
VelocityFieldDirectionType m_Direction
double m_ExtrapolationSigma
VelocityFieldRegionType m_LargestRegion
unsigned int m_NumberOfThreads
VelocityFieldPointType m_Origin
double m_OutlierRejectionSigma
VelocityFieldSpacingType m_Spacing
Additional Inherited Members
Protected Member Functions inherited from anima::BaseTransformAgregator< NDimensions >
void SetOutput (BaseOutputTransformType *output)
Detailed Description
template<unsigned int NDimensions = 3>
class anima::BalooSVFTransformAgregator< NDimensions >
Definition at line 11 of file animaBalooSVFTransformAgregator.h.
Member Typedef Documentation
template<unsigned int NDimensions = 3> typedef Superclass::BaseInputTransformType anima::BalooSVFTransformAgregator< NDimensions >::BaseInputTransformType
Definition at line 17 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef itk::MatrixOffsetTransformBase<InternalScalarType, NDimensions, NDimensions> anima::BalooSVFTransformAgregator< NDimensions >::BaseMatrixTransformType
Definition at line 26 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef itk::StationaryVelocityFieldTransform<ScalarType,NDimensions> anima::BalooSVFTransformAgregator< NDimensions >::BaseOutputTransformType
Definition at line 19 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef WeightImageType::IndexType anima::BalooSVFTransformAgregator< NDimensions >::IndexType
Definition at line 23 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::InternalScalarType anima::BalooSVFTransformAgregator< NDimensions >::InternalScalarType
Definition at line 20 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef BaseMatrixTransformType::ParametersType anima::BalooSVFTransformAgregator< NDimensions >::ParametersType
Definition at line 27 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::PointType anima::BalooSVFTransformAgregator< NDimensions >::PointType
Definition at line 16 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::ScalarType anima::BalooSVFTransformAgregator< NDimensions >::ScalarType
Definition at line 18 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef BaseTransformAgregator<NDimensions> anima::BalooSVFTransformAgregator< NDimensions >::Superclass
Definition at line 15 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef VelocityFieldType::DirectionType anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldDirectionType
Definition at line 36 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef VelocityFieldType::IndexType anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldIndexType
Definition at line 31 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef VelocityFieldType::PixelType anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldPixelType
Definition at line 32 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef VelocityFieldType::Pointer anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldPointer
Definition at line 30 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef VelocityFieldType::PointType anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldPointType
Definition at line 33 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef VelocityFieldType::RegionType anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldRegionType
Definition at line 34 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef VelocityFieldType::SpacingType anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldSpacingType
Definition at line 35 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef BaseOutputTransformType::VectorFieldType anima::BalooSVFTransformAgregator< NDimensions >::VelocityFieldType
Definition at line 29 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef WeightImageType::Pointer anima::BalooSVFTransformAgregator< NDimensions >::WeightImagePointer
Definition at line 24 of file animaBalooSVFTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef itk::Image<ScalarType,NDimensions> anima::BalooSVFTransformAgregator< NDimensions >::WeightImageType
Definition at line 22 of file animaBalooSVFTransformAgregator.h.
Constructor & Destructor Documentation
template<unsigned int NDimensions> anima::BalooSVFTransformAgregator< NDimensions >::BalooSVFTransformAgregator ()
Definition at line 21 of file animaBalooSVFTransformAgregator.hxx.
References anima::BalooSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma, anima::BalooSVFTransformAgregator< NDimensions >::m_NumberOfThreads, and anima::BalooSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma.
template<unsigned int NDimensions = 3> virtual anima::BalooSVFTransformAgregator< NDimensions >::~BalooSVFTransformAgregator () inline virtual
Definition at line 39 of file animaBalooSVFTransformAgregator.h.
Member Function Documentation
template<unsigned int NDimensions = 3> double anima::BalooSVFTransformAgregator< NDimensions >::GetExtrapolationSigma () inline
Definition at line 44 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma.
Referenced by anima::filterInputs().
template<unsigned int NDimensions = 3> unsigned int anima::BalooSVFTransformAgregator< NDimensions >::GetNumberOfThreads () inline
Definition at line 50 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_NumberOfThreads.
Referenced by anima::filterInputs().
template<unsigned int NDimensions = 3> double anima::BalooSVFTransformAgregator< NDimensions >::GetOutlierRejectionSigma () inline
Definition at line 47 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma.
Referenced by anima::filterInputs().
template<unsigned int NDimensions = 3> void anima::BalooSVFTransformAgregator< NDimensions >::SetDamIndexes (std::vector< IndexType > & indexes) inline
Definition at line 52 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_DamIndexes.
Referenced by anima::AsymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration(), anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration(), anima::SymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration(), and anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::PerformOneIteration().
template<unsigned int NDimensions = 3> void anima::BalooSVFTransformAgregator< NDimensions >::SetExtrapolationSigma (double sigma) inline
Definition at line 43 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update().
template<unsigned int NDimensions = 3> template<class TInputImageType > void anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation (const TInputImageType * geomImage) inline
Definition at line 54 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_Direction, anima::BalooSVFTransformAgregator< NDimensions >::m_LargestRegion, anima::BalooSVFTransformAgregator< NDimensions >::m_Origin, and anima::BalooSVFTransformAgregator< NDimensions >::m_Spacing.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update().
template<unsigned int NDimensions = 3> void anima::BalooSVFTransformAgregator< NDimensions >::SetNumberOfThreads (unsigned int num) inline
Definition at line 49 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_NumberOfThreads.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update().
template<unsigned int NDimensions = 3> void anima::BalooSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma (double sigma) inline
Definition at line 46 of file animaBalooSVFTransformAgregator.h.
References anima::BalooSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update().
template<unsigned int NDimensions> bool anima::BalooSVFTransformAgregator< NDimensions >::Update () virtual
Implements anima::BaseTransformAgregator< NDimensions >.
Definition at line 32 of file animaBalooSVFTransformAgregator.hxx.
Member Data Documentation
template<unsigned int NDimensions = 3> std::vector<IndexType> anima::BalooSVFTransformAgregator< NDimensions >::m_DamIndexes protected
Definition at line 75 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::SetDamIndexes().
template<unsigned int NDimensions = 3> VelocityFieldDirectionType anima::BalooSVFTransformAgregator< NDimensions >::m_Direction protected
Definition at line 72 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation().
template<unsigned int NDimensions = 3> double anima::BalooSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma protected
Definition at line 66 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::BalooSVFTransformAgregator(), anima::BalooSVFTransformAgregator< NDimensions >::GetExtrapolationSigma(), and anima::BalooSVFTransformAgregator< NDimensions >::SetExtrapolationSigma().
template<unsigned int NDimensions = 3> VelocityFieldRegionType anima::BalooSVFTransformAgregator< NDimensions >::m_LargestRegion protected
Definition at line 70 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation().
template<unsigned int NDimensions = 3> unsigned int anima::BalooSVFTransformAgregator< NDimensions >::m_NumberOfThreads protected
Definition at line 74 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::BalooSVFTransformAgregator(), anima::BalooSVFTransformAgregator< NDimensions >::GetNumberOfThreads(), and anima::BalooSVFTransformAgregator< NDimensions >::SetNumberOfThreads().
template<unsigned int NDimensions = 3> VelocityFieldPointType anima::BalooSVFTransformAgregator< NDimensions >::m_Origin protected
Definition at line 69 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation().
template<unsigned int NDimensions = 3> double anima::BalooSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma protected
Definition at line 67 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::BalooSVFTransformAgregator(), anima::BalooSVFTransformAgregator< NDimensions >::GetOutlierRejectionSigma(), and anima::BalooSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma().
template<unsigned int NDimensions = 3> VelocityFieldSpacingType anima::BalooSVFTransformAgregator< NDimensions >::m_Spacing protected
Definition at line 71 of file animaBalooSVFTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation().
The documentation for this class was generated from the following files:
animaBalooSVFTransformAgregator.h
animaBalooSVFTransformAgregator.hxx