ANIMA: anima::DTIEstimationImageFilter< PixelScalarType > Class Template Reference
anima::DTIEstimationImageFilter< PixelScalarType > Class Template Reference
#include <animaDTIEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef OutputImageType DTIImageType
typedef itk::Image
< PixelScalarType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef itk::Image
< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef InputImageType OutputB0ImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::VectorImage
< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
DTIEstimationImageFilter
< PixelScalarType > Self
typedef
anima::MaskedImageToImageFilter
< InputImageType,
OutputImageType > Superclass
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef MaskImageType::RegionType MaskRegionType
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef RegionSplitterType::Pointer RegionSplitterPointer
typedef
anima::ImageRegionSplitterMask
< MaskImageType > RegionSplitterType
typedef MaskedImageToImageFilter Self
typedef
itk::ImageToImageFilter
< itk::Image< PixelScalarType, 3 >
, itk::VectorImage
< PixelScalarType, 3 > > Superclass
Public Member Functions
void AddGradientDirection (unsigned int i, vnl_vector_fixed< double, 3 > &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual float GetB0Threshold ()
virtual OutputB0ImageType * GetEstimatedB0Image ()
virtual const char * GetNameOfClass () const
virtual void SetB0Threshold (float _arg)
void SetBValuesList (std::vector< double > bValuesList)
virtual void SetRemoveDegeneratedTensors (bool _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetActualNumberOfThreads ()
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData ()
void CheckComputationMask ()
DTIEstimationImageFilter ()
void GenerateOutputInformation (void)
void PrintSelf (std::ostream &os, itk::Indent indent) const
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
virtual ~DTIEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >
virtual const
itk::ImageRegionSplitterBase * GetImageRegionSplitter (void) const
void InitializeComputationRegionFromMask ()
void InitializeZeroPixel (itk::VectorImage< PixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::VectorImage< PixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual ~MaskedImageToImageFilter ()
Detailed Description
template<class PixelScalarType>
class anima::DTIEstimationImageFilter< PixelScalarType >
Definition at line 11 of file animaDTIEstimationImageFilter.h.
Member Typedef Documentation
template<class PixelScalarType > typedef itk::SmartPointer<const Self> anima::DTIEstimationImageFilter< PixelScalarType >::ConstPointer
Definition at line 24 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef OutputImageType anima::DTIEstimationImageFilter< PixelScalarType >::DTIImageType
Definition at line 20 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::Image<PixelScalarType,4> anima::DTIEstimationImageFilter< PixelScalarType >::Image4DType
Definition at line 21 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef InputImageType::Pointer anima::DTIEstimationImageFilter< PixelScalarType >::InputImagePointer
Image typedef support
Definition at line 30 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef Superclass::InputImageRegionType anima::DTIEstimationImageFilter< PixelScalarType >::InputImageRegionType
Definition at line 38 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::Image<PixelScalarType,3> anima::DTIEstimationImageFilter< PixelScalarType >::InputImageType
Definition at line 17 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef Superclass::MaskImageType anima::DTIEstimationImageFilter< PixelScalarType >::MaskImageType
Superclass typedefs.
Definition at line 37 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef InputImageType anima::DTIEstimationImageFilter< PixelScalarType >::OutputB0ImageType
Definition at line 19 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef OutputImageType::Pointer anima::DTIEstimationImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 34 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef Superclass::OutputImageRegionType anima::DTIEstimationImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 39 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::VectorImage<PixelScalarType,3> anima::DTIEstimationImageFilter< PixelScalarType >::OutputImageType
Definition at line 18 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef itk::SmartPointer<Self> anima::DTIEstimationImageFilter< PixelScalarType >::Pointer
Definition at line 23 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef DTIEstimationImageFilter<PixelScalarType> anima::DTIEstimationImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 16 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::DTIEstimationImageFilter< PixelScalarType >::Superclass
Definition at line 22 of file animaDTIEstimationImageFilter.h.
Constructor & Destructor Documentation
template<class PixelScalarType > anima::DTIEstimationImageFilter< PixelScalarType >::DTIEstimationImageFilter () inline protected
Definition at line 53 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > virtual anima::DTIEstimationImageFilter< PixelScalarType >::~DTIEstimationImageFilter () inline protected virtual
Definition at line 64 of file animaDTIEstimationImageFilter.h.
Member Function Documentation
template<class PixelScalarType > void anima::DTIEstimationImageFilter< PixelScalarType >::AddGradientDirection (unsigned int i, vnl_vector_fixed< double, 3 > & grad)
Definition at line 23 of file animaDTIEstimationImageFilter.hxx.
template<class PixelScalarType > void anima::DTIEstimationImageFilter< PixelScalarType >::BeforeThreadedGenerateData (void) protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 88 of file animaDTIEstimationImageFilter.hxx.
References anima::ComputeNorm(), and anima::ComputeScalarProduct().
template<class PixelScalarType > void anima::DTIEstimationImageFilter< PixelScalarType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 36 of file animaDTIEstimationImageFilter.hxx.
template<class PixelScalarType > virtual::itk::LightObject::Pointer anima::DTIEstimationImageFilter< PixelScalarType >::CreateAnother (void) const
template<class PixelScalarType > void anima::DTIEstimationImageFilter< PixelScalarType >::GenerateOutputInformation (void) protected
Definition at line 74 of file animaDTIEstimationImageFilter.hxx.
template<class PixelScalarType > virtual float anima::DTIEstimationImageFilter< PixelScalarType >::GetB0Threshold () virtual
template<class PixelScalarType > virtual OutputB0ImageType* anima::DTIEstimationImageFilter< PixelScalarType >::GetEstimatedB0Image () virtual
template<class PixelScalarType > virtual const char* anima::DTIEstimationImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
template<class PixelScalarType > static Pointer anima::DTIEstimationImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
template<class PixelScalarType > void anima::DTIEstimationImageFilter< PixelScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const inline protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< PixelScalarType, 3 >, itk::VectorImage< PixelScalarType, 3 > >.
Definition at line 72 of file animaDTIEstimationImageFilter.h.
References anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::PrintSelf().
template<class PixelScalarType > virtual void anima::DTIEstimationImageFilter< PixelScalarType >::SetB0Threshold (float _arg) virtual
template<class PixelScalarType > void anima::DTIEstimationImageFilter< PixelScalarType >::SetBValuesList (std::vector< double > bValuesList) inline
Definition at line 41 of file animaDTIEstimationImageFilter.h.
template<class PixelScalarType > virtual void anima::DTIEstimationImageFilter< PixelScalarType >::SetRemoveDegeneratedTensors (bool _arg) virtual
template<class PixelScalarType > void anima::DTIEstimationImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 194 of file animaDTIEstimationImageFilter.hxx.
References anima::GetTensorFromVectorRepresentation().
The documentation for this class was generated from the following files:
animaDTIEstimationImageFilter.h
animaDTIEstimationImageFilter.hxx