ANIMA: anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType > Class Template Reference
anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType > Class Template Reference
#include <animaNLMeansVectorPatchSearcher.h>
Public Types
typedef vnl_matrix< double > CovarianceType
typedef DataImageType::Pointer DataImagePointer
typedef Superclass::ImageRegionType ImageRegionType
typedef Superclass::IndexType IndexType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef itk::VectorImage
< ImageScalarType,
DataImageType::ImageDimension > RefImageType
typedef
anima::NonLocalPatchBaseSearcher
< RefImageType > Superclass
typedef RefImageType::PixelType VectorType
Public Types inherited from anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >
typedef itk::VectorImage
< ImageScalarType,
DataImageType::ImageDimension >
::Pointer ImagePointer
typedef itk::VectorImage
< ImageScalarType,
DataImageType::ImageDimension >
::RegionType ImageRegionType
typedef itk::VectorImage
< ImageScalarType,
DataImageType::ImageDimension >
::IndexType IndexType
typedef itk::VectorImage
< ImageScalarType,
DataImageType::ImageDimension >
::PixelType PixelType
typedef itk::VectorImage
< ImageScalarType,
DataImageType::ImageDimension >
::SizeType SizeType
Public Member Functions
NLMeansVectorPatchSearcher ()
void SetBetaParameter (double arg)
void SetDatabaseCovarianceDistanceAverage (DataImagePointer &arg)
void SetDatabaseCovarianceDistanceStd (DataImagePointer &arg)
void SetDatabaseMeanDistanceAverage (DataImagePointer &arg)
void SetDatabaseMeanDistanceStd (DataImagePointer &arg)
void SetDataMask (MaskImageType *arg)
void SetMeanThreshold (double arg)
void SetVarianceThreshold (double arg)
virtual ~NLMeansVectorPatchSearcher ()
Public Member Functions inherited from anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >
void AddComparisonImage (itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > *arg)
itk::VectorImage
< ImageScalarType,
DataImageType::ImageDimension > * GetComparisonImage (unsigned int index)
virtual const std::vector
< PixelType > & GetDatabaseSamples () const
virtual const std::vector
< double > & GetDatabaseWeights () const
itkGetObjectMacro (InputImage, itk::VectorImage< ImageScalarType, DataImageType::ImageDimension >)
NonLocalPatchBaseSearcher ()
void SetInputImage (itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > *arg)
void SetMaxAbsDisp (unsigned int arg)
void SetPatchHalfSize (unsigned int arg)
void SetSearchStepSize (unsigned int arg)
void SetWeightThreshold (double arg)
void UpdateAtPosition (const IndexType &dataIndex)
virtual ~NonLocalPatchBaseSearcher ()
Protected Member Functions
virtual void ComputeComparisonProperties (unsigned int index, ImageRegionType &movingPatch)
virtual void ComputeInputProperties (const IndexType &refIndex, ImageRegionType &refPatch)
virtual double ComputeWeightValue (unsigned int index, ImageRegionType &refPatch, ImageRegionType &movingPatch)
virtual bool TestPatchConformity (unsigned int index, const IndexType &refIndex, const IndexType &movingIndex)
Protected Member Functions inherited from anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >
virtual void ComputeComparisonProperties (unsigned int index, ImageRegionType &movingPatch)
virtual void ComputeInputProperties (const IndexType &refIndex, ImageRegionType &refPatch)
virtual double ComputeWeightValue (unsigned int index, ImageRegionType &refPatch, ImageRegionType &movingPatch)=0
virtual bool TestPatchConformity (unsigned int index, const IndexType &refIndex, const IndexType &movingIndex)=0
Detailed Description
template<class ImageScalarType, class DataImageType>
class anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >
Definition at line 10 of file animaNLMeansVectorPatchSearcher.h.
Member Typedef Documentation
template<class ImageScalarType , class DataImageType > typedef vnl_matrix<double> anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::CovarianceType
Definition at line 16 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef DataImageType::Pointer anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::DataImagePointer
Definition at line 21 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef Superclass::ImageRegionType anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::ImageRegionType
Definition at line 23 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef Superclass::IndexType anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::IndexType
Definition at line 24 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef MaskImageType::Pointer anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::MaskImagePointer
Definition at line 19 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef itk::Image<unsigned char, 3> anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::MaskImageType
Definition at line 18 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef itk::VectorImage<ImageScalarType,DataImageType::ImageDimension> anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::RefImageType
Definition at line 14 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef anima::NonLocalPatchBaseSearcher<RefImageType> anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::Superclass
Definition at line 22 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > typedef RefImageType::PixelType anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::VectorType
Definition at line 15 of file animaNLMeansVectorPatchSearcher.h.
Constructor & Destructor Documentation
template<class ImageScalarType , class DataImageType > anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::NLMeansVectorPatchSearcher ()
Definition at line 13 of file animaNLMeansVectorPatchSearcher.hxx.
template<class ImageScalarType , class DataImageType > virtual anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::~NLMeansVectorPatchSearcher () inline virtual
Definition at line 27 of file animaNLMeansVectorPatchSearcher.h.
Member Function Documentation
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::ComputeComparisonProperties (unsigned int index, ImageRegionType & movingPatch) protected virtual
Definition at line 62 of file animaNLMeansVectorPatchSearcher.hxx.
References anima::computePatchMeanAndCovariance().
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::ComputeInputProperties (const IndexType & refIndex, ImageRegionType & refPatch) protected virtual
Definition at line 24 of file animaNLMeansVectorPatchSearcher.hxx.
References anima::computeAverageLocalCovariance(), and anima::computePatchMeanAndCovariance().
template<class ImageScalarType , class DataImageType > double anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::ComputeWeightValue (unsigned int index, ImageRegionType & refPatch, ImageRegionType & movingPatch) protected virtual
Definition at line 102 of file animaNLMeansVectorPatchSearcher.hxx.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetBetaParameter (double arg) inline
Definition at line 29 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetDatabaseCovarianceDistanceAverage (DataImagePointer & arg) inline
Definition at line 35 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetDatabaseCovarianceDistanceStd (DataImagePointer & arg) inline
Definition at line 36 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetDatabaseMeanDistanceAverage (DataImagePointer & arg) inline
Definition at line 37 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetDatabaseMeanDistanceStd (DataImagePointer & arg) inline
Definition at line 38 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetDataMask (MaskImageType * arg) inline
Definition at line 33 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetMeanThreshold (double arg) inline
Definition at line 30 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > void anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::SetVarianceThreshold (double arg) inline
Definition at line 31 of file animaNLMeansVectorPatchSearcher.h.
template<class ImageScalarType , class DataImageType > bool anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::TestPatchConformity (unsigned int index, const IndexType & refIndex, const IndexType & movingIndex) protected virtual
Definition at line 78 of file animaNLMeansVectorPatchSearcher.hxx.
References anima::VectorCovarianceTest(), and anima::VectorMeansTest().
The documentation for this class was generated from the following files:
animaNLMeansVectorPatchSearcher.h
animaNLMeansVectorPatchSearcher.hxx