ANIMA: anima::ImageDataSplitter< TInputImage > Class Template Reference
anima::ImageDataSplitter< TInputImage > Class Template Reference
#include <animaImageDataSplitter.h>
Public Types
typedef InputReaderType::Pointer InputReaderPointer
typedef itk::ImageFileReader
< TInputImage > InputReaderType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef TInputImage::IndexType TInputIndexType
typedef TInputImage::Pointer TInputPointer
typedef TInputImage::RegionType TInputRegionType
Public Member Functions
bool EmptyMask (TInputIndexType &bIndex)
TInputRegionType GetBlockRegion ()
TInputRegionType GetBlockRegionInsideMargin ()
TInputRegionType GetBlockRegionWithMargin ()
std::string GetFileName (unsigned int i)
unsigned int GetNbImages ()
TInputImage * GetOutput (unsigned int i)
MaskImageType * GetSmallMask ()
MaskImageType * GetSmallMaskWithMargin ()
TInputRegionType GetSpecificBlockRegion (TInputIndexType &block)
ImageDataSplitter ()
void SetBlockIndex (TInputIndexType &bIndex)
void SetBlockMargin (TInputIndexType &bMargin)
void SetComputationMask (MaskImageType::Pointer &maskIm)
void SetFileNames (std::string &inputFileList)
void SetNumberOfBlocks (TInputIndexType &bNumBlocks)
void SetUniqueFileName (std::string &inputFileName)
void Update ()
~ImageDataSplitter ()
Detailed Description
template<class TInputImage>
class anima::ImageDataSplitter< TInputImage >
Definition at line 11 of file animaImageDataSplitter.h.
Member Typedef Documentation
template<class TInputImage > typedef InputReaderType::Pointer anima::ImageDataSplitter< TInputImage >::InputReaderPointer
Definition at line 20 of file animaImageDataSplitter.h.
template<class TInputImage > typedef itk::ImageFileReader<TInputImage> anima::ImageDataSplitter< TInputImage >::InputReaderType
Definition at line 19 of file animaImageDataSplitter.h.
template<class TInputImage > typedef MaskImageType::Pointer anima::ImageDataSplitter< TInputImage >::MaskImagePointer
Definition at line 22 of file animaImageDataSplitter.h.
template<class TInputImage > typedef itk::Image<unsigned char, 3> anima::ImageDataSplitter< TInputImage >::MaskImageType
Definition at line 14 of file animaImageDataSplitter.h.
template<class TInputImage > typedef TInputImage::IndexType anima::ImageDataSplitter< TInputImage >::TInputIndexType
Definition at line 15 of file animaImageDataSplitter.h.
template<class TInputImage > typedef TInputImage::Pointer anima::ImageDataSplitter< TInputImage >::TInputPointer
Definition at line 17 of file animaImageDataSplitter.h.
template<class TInputImage > typedef TInputImage::RegionType anima::ImageDataSplitter< TInputImage >::TInputRegionType
Definition at line 16 of file animaImageDataSplitter.h.
Constructor & Destructor Documentation
template<typename TInputImage > anima::ImageDataSplitter< TInputImage >::ImageDataSplitter ()
Definition at line 13 of file animaImageDataSplitter.hxx.
template<typename TInputImage > anima::ImageDataSplitter< TInputImage >::~ImageDataSplitter ()
Definition at line 38 of file animaImageDataSplitter.hxx.
Member Function Documentation
template<typename TInputImage > bool anima::ImageDataSplitter< TInputImage >::EmptyMask (TInputIndexType & bIndex)
Definition at line 171 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<class TInputImage > TInputRegionType anima::ImageDataSplitter< TInputImage >::GetBlockRegion () inline
Definition at line 41 of file animaImageDataSplitter.h.
References anima::ImageDataSplitter< TInputImage >::Update().
template<typename TInputImage > TInputImage::RegionType anima::ImageDataSplitter< TInputImage >::GetBlockRegionInsideMargin ()
Definition at line 304 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<class TInputImage > TInputRegionType anima::ImageDataSplitter< TInputImage >::GetBlockRegionWithMargin () inline
Definition at line 42 of file animaImageDataSplitter.h.
References anima::ImageDataSplitter< TInputImage >::Update().
template<class TInputImage > std::string anima::ImageDataSplitter< TInputImage >::GetFileName (unsigned int i) inline
Definition at line 29 of file animaImageDataSplitter.h.
template<class TInputImage > unsigned int anima::ImageDataSplitter< TInputImage >::GetNbImages () inline
Definition at line 48 of file animaImageDataSplitter.h.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<class TInputImage > TInputImage* anima::ImageDataSplitter< TInputImage >::GetOutput (unsigned int i) inline
Definition at line 47 of file animaImageDataSplitter.h.
References anima::ImageDataSplitter< TInputImage >::Update().
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<class TInputImage > MaskImageType* anima::ImageDataSplitter< TInputImage >::GetSmallMask () inline
Definition at line 45 of file animaImageDataSplitter.h.
References anima::ImageDataSplitter< TInputImage >::Update().
template<class TInputImage > MaskImageType* anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin () inline
Definition at line 46 of file animaImageDataSplitter.h.
References anima::ImageDataSplitter< TInputImage >::Update().
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<typename TInputImage > TInputImage::RegionType anima::ImageDataSplitter< TInputImage >::GetSpecificBlockRegion (TInputIndexType & block)
Definition at line 157 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<typename TInputImage > void anima::ImageDataSplitter< TInputImage >::SetBlockIndex (TInputIndexType & bIndex)
Definition at line 139 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<typename TInputImage > void anima::ImageDataSplitter< TInputImage >::SetBlockMargin (TInputIndexType & bMargin)
Definition at line 148 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<typename TInputImage > void anima::ImageDataSplitter< TInputImage >::SetComputationMask (MaskImageType::Pointer & maskIm)
Definition at line 80 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetComputationMask(), anima::LowMemoryPatientToGroupODFComparisonBridge::SetComputationMask(), anima::LowMemoryPatientToGroupComparisonBridge::SetComputationMask(), anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetComputationMask(), and anima::LowMemoryLocalPatchMeanDistanceBridge::SetComputationMask().
template<typename TInputImage > void anima::ImageDataSplitter< TInputImage >::SetFileNames (std::string & inputFileList)
Definition at line 51 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseNames(), anima::LowMemoryLocalPatchMeanDistanceBridge::SetDatabaseNames(), anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetDatabaseNames(), anima::LowMemoryPatientToGroupComparisonBridge::SetDataLTFileNames(), and anima::LowMemoryPatientToGroupODFComparisonBridge::SetDataODFFileNames().
template<typename TInputImage > void anima::ImageDataSplitter< TInputImage >::SetNumberOfBlocks (TInputIndexType & bNumBlocks)
Definition at line 130 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
template<typename TInputImage > void anima::ImageDataSplitter< TInputImage >::SetUniqueFileName (std::string & inputFileName)
Definition at line 44 of file animaImageDataSplitter.hxx.
Referenced by anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseCovarianceDistanceAverageFileName(), anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseCovarianceDistanceStdFileName(), anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseMeanDistanceAverageFileName(), anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseMeanDistanceStdFileName(), anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetTestFileName(), anima::LowMemoryPatientToGroupComparisonBridge::SetTestLTFileName(), and anima::LowMemoryPatientToGroupODFComparisonBridge::SetTestODFFileName().
template<typename TInputImage > void anima::ImageDataSplitter< TInputImage >::Update ()
Definition at line 194 of file animaImageDataSplitter.hxx.
Referenced by anima::ImageDataSplitter< TInputImage >::GetBlockRegion(), anima::ImageDataSplitter< TInputImage >::GetBlockRegionWithMargin(), anima::ImageDataSplitter< TInputImage >::GetOutput(), anima::ImageDataSplitter< TInputImage >::GetSmallMask(), anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin(), anima::LowMemoryLocalPatchMeanDistanceBridge::Update(), anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update(), anima::LowMemoryPatientToGroupComparisonBridge::Update(), anima::LowMemoryPatientToGroupODFComparisonBridge::Update(), and anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
The documentation for this class was generated from the following files:
animaImageDataSplitter.h
animaImageDataSplitter.hxx