ANIMA: anima::DTIExtrapolateImageFilter< PixelScalarType > Class Template Reference
anima::DTIExtrapolateImageFilter< PixelScalarType > Class Template Reference
#include <animaDTIExtrapolateImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::VectorImage
< PixelScalarType, 3 > DTIImageType
typedef InputImageType::Pointer InputImagePointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef itk::Image
< PixelScalarType, 3 > OutputB0ImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
DTIExtrapolateImageFilter
< PixelScalarType > Self
typedef
itk::ImageToImageFilter
< TInputImage, TOutputImage > Superclass
typedef itk::VectorImage
< PixelScalarType, 3 > TInputImage
typedef itk::VectorImage
< PixelScalarType, 3 > TOutputImage
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual OutputB0ImageType * GetEstimatedB0Image ()
virtual const char * GetNameOfClass () const
void SetInitialEstimatedB0Image (OutputB0ImageType *b0)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData ()
DTIExtrapolateImageFilter ()
void GenerateOutputInformation (void)
void PrintSelf (std::ostream &os, itk::Indent indent) const
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
virtual ~DTIExtrapolateImageFilter ()
Detailed Description
template<class PixelScalarType>
class anima::DTIExtrapolateImageFilter< PixelScalarType >
Definition at line 11 of file animaDTIExtrapolateImageFilter.h.
Member Typedef Documentation
template<class PixelScalarType > typedef itk::SmartPointer<const Self> anima::DTIExtrapolateImageFilter< PixelScalarType >::ConstPointer
Definition at line 23 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef itk::VectorImage<PixelScalarType,3> anima::DTIExtrapolateImageFilter< PixelScalarType >::DTIImageType
Definition at line 19 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef InputImageType::Pointer anima::DTIExtrapolateImageFilter< PixelScalarType >::InputImagePointer
Definition at line 34 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef Superclass::InputImageRegionType anima::DTIExtrapolateImageFilter< PixelScalarType >::InputImageRegionType
Superclass typedefs.
Definition at line 38 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef TInputImage anima::DTIExtrapolateImageFilter< PixelScalarType >::InputImageType
Image typedef support
Definition at line 29 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef itk::Image<PixelScalarType,3> anima::DTIExtrapolateImageFilter< PixelScalarType >::OutputB0ImageType
Definition at line 18 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef OutputImageType::Pointer anima::DTIExtrapolateImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 35 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef Superclass::OutputImageRegionType anima::DTIExtrapolateImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 39 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef TOutputImage anima::DTIExtrapolateImageFilter< PixelScalarType >::OutputImageType
Definition at line 33 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef itk::SmartPointer<Self> anima::DTIExtrapolateImageFilter< PixelScalarType >::Pointer
Definition at line 22 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef DTIExtrapolateImageFilter<PixelScalarType> anima::DTIExtrapolateImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 16 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::DTIExtrapolateImageFilter< PixelScalarType >::Superclass
Definition at line 21 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef itk::VectorImage<PixelScalarType,3> anima::DTIExtrapolateImageFilter< PixelScalarType >::TInputImage
Definition at line 17 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > typedef itk::VectorImage<PixelScalarType,3> anima::DTIExtrapolateImageFilter< PixelScalarType >::TOutputImage
Definition at line 20 of file animaDTIExtrapolateImageFilter.h.
Constructor & Destructor Documentation
template<class PixelScalarType > anima::DTIExtrapolateImageFilter< PixelScalarType >::DTIExtrapolateImageFilter () inline protected
Definition at line 45 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > virtual anima::DTIExtrapolateImageFilter< PixelScalarType >::~DTIExtrapolateImageFilter () inline protected virtual
Definition at line 51 of file animaDTIExtrapolateImageFilter.h.
Member Function Documentation
template<class PixelScalarType > void anima::DTIExtrapolateImageFilter< PixelScalarType >::BeforeThreadedGenerateData (void) protected
Definition at line 31 of file animaDTIExtrapolateImageFilter.hxx.
template<class PixelScalarType > virtual::itk::LightObject::Pointer anima::DTIExtrapolateImageFilter< PixelScalarType >::CreateAnother (void) const
template<class PixelScalarType > void anima::DTIExtrapolateImageFilter< PixelScalarType >::GenerateOutputInformation (void) protected
Definition at line 17 of file animaDTIExtrapolateImageFilter.hxx.
template<class PixelScalarType > virtual OutputB0ImageType* anima::DTIExtrapolateImageFilter< PixelScalarType >::GetEstimatedB0Image () virtual
template<class PixelScalarType > virtual const char* anima::DTIExtrapolateImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
template<class PixelScalarType > static Pointer anima::DTIExtrapolateImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
template<class PixelScalarType > void anima::DTIExtrapolateImageFilter< PixelScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const inline protected
Definition at line 57 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > void anima::DTIExtrapolateImageFilter< PixelScalarType >::SetInitialEstimatedB0Image (OutputB0ImageType * b0) inline
Definition at line 41 of file animaDTIExtrapolateImageFilter.h.
template<class PixelScalarType > void anima::DTIExtrapolateImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 55 of file animaDTIExtrapolateImageFilter.hxx.
References anima::GetTensorExponential(), anima::GetTensorFromVectorRepresentation(), anima::GetTensorLogarithm(), and anima::GetVectorRepresentation().
The documentation for this class was generated from the following files:
animaDTIExtrapolateImageFilter.h
animaDTIExtrapolateImageFilter.hxx