ANIMA: anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType > Class Template Reference
anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType > Class Template Reference
#include <animaResampleImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef TOutputImage::DirectionType DirectionType
typedef itk::ImageBase
< itkGetStaticConstMacro(ImageDimension)> ImageBaseType
typedef TOutputImage::IndexType IndexType
typedef
InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef TInputImage InputImageType
typedef InputImageType::IndexType InputIndexType
typedef TInputImage::PixelType InputPixelType
typedef InterpolatorType::Pointer InterpolatorPointerType
typedef
itk::InterpolateImageFunction
< InputImageType,
TInterpolatorPrecisionType > InterpolatorType
typedef
itk::MatrixOffsetTransformBase
< TInterpolatorPrecisionType,
itkGetStaticConstMacro(ImageDimension),
itkGetStaticConstMacro(ImageDimension)> MatrixTransformType
typedef TOutputImage::PointType OriginPointType
typedef OutputImageType::Pointer OutputImagePointer
typedef TOutputImage::RegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef TOutputImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef InterpolatorType::PointType PointType
typedef ResampleImageFilter Self
typedef itk::Size
< itkGetStaticConstMacro(ImageDimension)> SizeType
typedef TOutputImage::SpacingType SpacingType
typedef
itk::ImageToImageFilter
< TInputImage, TOutputImage > Superclass
typedef TransformType::ConstPointer TransformPointerType
typedef itk::Transform
< TInterpolatorPrecisionType,
itkGetStaticConstMacro(ImageDimension),
itkGetStaticConstMacro(ImageDimension)> TransformType
Public Member Functions
virtual void AfterThreadedGenerateData (void)
virtual void BeforeThreadedGenerateData (void)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GenerateInputRequestedRegion (void)
virtual void GenerateOutputInformation (void)
virtual const PixelType & GetDefaultPixelValue () const
virtual const InterpolatorType * GetInterpolator () const
unsigned long GetMTime (void) const
virtual const char * GetNameOfClass () const
virtual const DirectionType & GetOutputDirection () const
virtual const OriginPointType & GetOutputOrigin () const
virtual const SpacingType & GetOutputSpacing () const
virtual const IndexType & GetOutputStartIndex () const
const TOutputImage * GetReferenceImage (void) const
virtual const SizeType & GetSize () const
virtual const TransformType * GetTransform () const
virtual bool GetUseReferenceImage () const
itkLegacyMacro (void SetOutputParametersFromConstImage(const ImageBaseType *image))
virtual void SetDefaultPixelValue (PixelType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetOutputDirection (DirectionType _arg)
virtual void SetOutputOrigin (OriginPointType _arg)
virtual void SetOutputOrigin (const double *values)
void SetOutputParametersFromImage (const ImageBaseType *image)
virtual void SetOutputSpacing (SpacingType _arg)
virtual void SetOutputSpacing (const double *values)
virtual void SetOutputStartIndex (IndexType _arg)
void SetReferenceImage (const TOutputImage *image)
void SetScaleIntensitiesWithJacobian (bool scale)
virtual void SetSize (SizeType _arg)
void SetTransform (TransformType *transform)
virtual void SetUseReferenceImage (bool _arg)
virtual void UseReferenceImageOff ()
virtual void UseReferenceImageOn ()
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = TOutputImage::ImageDimension
static const unsigned int InputImageDimension = TInputImage::ImageDimension
Protected Member Functions
double ComputeLinearJacobianValue ()
double ComputeLocalJacobianValue (const InputIndexType &index)
virtual itk::LightObject::Pointer InternalClone () const
void PrintSelf (std::ostream &os, itk::Indent indent) const
ResampleImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
virtual ~ResampleImageFilter ()
Detailed Description
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double>
class anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >
Definition at line 17 of file animaResampleImageFilter.h.
Member Typedef Documentation
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::SmartPointer<const Self> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::ConstPointer
Definition at line 25 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TOutputImage::DirectionType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::DirectionType
Definition at line 81 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::ImageBase<itkGetStaticConstMacro(ImageDimension)> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::ImageBaseType
base type for images of the current ImageDimension
Definition at line 84 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TOutputImage::IndexType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::IndexType
Image index typedef.
Definition at line 65 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef InputImageType::ConstPointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InputImageConstPointer
Definition at line 30 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef InputImageType::Pointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InputImagePointer
Definition at line 29 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef InputImageType::RegionType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InputImageRegionType
Definition at line 32 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TInputImage anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InputImageType
Definition at line 27 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef InputImageType::IndexType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InputIndexType
Definition at line 33 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TInputImage::PixelType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InputPixelType
Definition at line 73 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef InterpolatorType::Pointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InterpolatorPointerType
Definition at line 59 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::InterpolateImageFunction<InputImageType, TInterpolatorPrecisionType> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InterpolatorType
Interpolator typedef.
Definition at line 58 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::MatrixOffsetTransformBase<TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::MatrixTransformType
Definition at line 55 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TOutputImage::PointType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::OriginPointType
Definition at line 80 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef OutputImageType::Pointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::OutputImagePointer
Definition at line 31 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TOutputImage::RegionType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::OutputImageRegionType
Typedef to describe the output image region type.
Definition at line 76 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TOutputImage anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::OutputImageType
Definition at line 28 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TOutputImage::PixelType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::PixelType
Image pixel value typedef.
Definition at line 72 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::SmartPointer<Self> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::Pointer
Definition at line 24 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef InterpolatorType::PointType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::PointType
Image point typedef.
Definition at line 68 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef ResampleImageFilter anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::Self
Standard class typedefs.
Definition at line 22 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::Size<itkGetStaticConstMacro(ImageDimension)> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SizeType
Image size typedef.
Definition at line 62 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TOutputImage::SpacingType anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SpacingType
Image spacing,origin and direction typedef
Definition at line 79 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::ImageToImageFilter<TInputImage,TOutputImage> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::Superclass
Definition at line 23 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef TransformType::ConstPointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::TransformPointerType
Definition at line 51 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> typedef itk::Transform<TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::TransformType
Transform typedef.
Definition at line 50 of file animaResampleImageFilter.h.
Constructor & Destructor Documentation
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::ResampleImageFilter () protected
Initialize new instance
Definition at line 22 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::~ResampleImageFilter () inline protected virtual
Definition at line 196 of file animaResampleImageFilter.h.
Member Function Documentation
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::AfterThreadedGenerateData (void) virtual
This method is used to set the state of the filter after multi-threading.
Set up state of filter after multi-threading.
Definition at line 156 of file animaResampleImageFilter.hxx.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::BeforeThreadedGenerateData (void) virtual
This method is used to set the state of the filter before multi-threading.
Set up state of filter before multi-threading. InterpolatorType::SetInputImage is not thread-safe and hence has to be set up before ThreadedGenerateData
Definition at line 133 of file animaResampleImageFilter.hxx.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > double anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::ComputeLinearJacobianValue () protected
Definition at line 416 of file animaResampleImageFilter.hxx.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > double anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::ComputeLocalJacobianValue (const InputIndexType & index) protected
Definition at line 435 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual::itk::LightObject::Pointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::CreateAnother (void) const
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GenerateInputRequestedRegion (void) virtual
ResampleImageFilter needs a different input requested region than the output requested region. As such, ResampleImageFilter needs to provide an implementation for GenerateInputRequestedRegion() in order to inform the pipeline execution model.
See Also
ProcessObject::GenerateInputRequestedRegion()
Inform pipeline of necessary input image region
Determining the actual input region is non-trivial, especially when we cannot assume anything about the transform being used. So we do the easy thing and request the entire input image.
Definition at line 267 of file animaResampleImageFilter.hxx.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GenerateOutputInformation (void) virtual
ResampleImageFilter produces an image which is a different size than its input. As such, it needs to provide an implementation for GenerateOutputInformation() in order to inform the pipeline execution model. The original documentation of this method is below.
See Also
ProcessObject::GenerateOutputInformaton()
Inform pipeline of required output region
Definition at line 341 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const PixelType& anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetDefaultPixelValue () const virtual
Get the pixel value when a transformed pixel is outside of the image
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const InterpolatorType* anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetInterpolator () const virtual
Get a pointer to the interpolator function.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > unsigned long anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetMTime (void) const
Method Compute the Modified Time based on changed to the components.
Verify if any of the components has been modified.
Definition at line 390 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const char* anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const DirectionType& anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetOutputDirection () const virtual
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const OriginPointType& anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetOutputOrigin () const virtual
Get the output image origin.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const SpacingType& anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetOutputSpacing () const virtual
Get the output image spacing.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const IndexType& anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetOutputStartIndex () const virtual
Get the start index of the output largest possible region.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > const ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::OutputImageType * anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetReferenceImage (void) const
Set the smart pointer to the reference image that will provide the grid parameters for the output image.
Definition at line 296 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const SizeType& anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetSize () const virtual
Get the size of the output image.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual const TransformType* anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetTransform () const virtual
Get a pointer to the coordinate transform.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual bool anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::GetUseReferenceImage () const virtual
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > itk::LightObject::Pointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InternalClone () const protected virtual
Returns a class copy with important specific variables set, not the greatest implementation especially in terms of interpolators and other internal pointers copy (not done here). Use with extreme caution
Definition at line 74 of file animaResampleImageFilter.hxx.
References anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetScaleIntensitiesWithJacobian().
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::itkLegacyMacro (void SetOutputParametersFromConstImageconst ImageBaseType *image)
Deprecated:
in ITK 3.14, Please use SetOutputParametersFromImage(). Helper method to set the output parameters based on this image.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> static Pointer anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::New () static
Method for creation through the object factory.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
Print out a description of self
Definition at line 48 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetDefaultPixelValue (PixelType _arg) virtual
Set the pixel value when a transformed pixel is outside of the image. The default default pixel value is 0.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetInterpolator (InterpolatorType * _arg) virtual
Set the interpolator function. The default is itk::LinearInterpolateImageFunction<InputImageType, TInterpolatorPrecisionType>. Some other options are itk::NearestNeighborInterpolateImageFunction (useful for binary masks and other images with a small number of possible pixel values), and itk::BSplineInterpolateImageFunction (which provides a higher order of interpolation).
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetOutputDirection (DirectionType _arg) virtual
Set the output direciton cosine matrix.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetOutputOrigin (OriginPointType _arg) virtual
Set the output image origin.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetOutputOrigin (const double * origin) virtual
Set the output image origin.
Definition at line 103 of file animaResampleImageFilter.hxx.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetOutputParametersFromImage (const ImageBaseType * image)
Helper method to set the output parameters based on this image
Definition at line 326 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetOutputSpacing (SpacingType _arg) virtual
Set the output image spacing.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetOutputSpacing (const double * spacing) virtual
Set the output image spacing.
Definition at line 90 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetOutputStartIndex (IndexType _arg) virtual
Set the start index of the output largest possible region. The default is an index of all zeros.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetReferenceImage (const TOutputImage * image)
Copy the output information from another Image. By default, the information is specified with the SetOutputSpacing, Origin, and Direction methods. UseReferenceImage must be On and a Reference image must be present to override the defaul behavior. NOTE: This function seems redundant with the SetOutputParametersFromImage(image) function
Set the smart pointer to the reference image that will provide the grid parameters for the output image.
Definition at line 312 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetScaleIntensitiesWithJacobian (bool scale) inline
Definition at line 192 of file animaResampleImageFilter.h.
Referenced by anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InternalClone().
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetSize (SizeType _arg) virtual
Set the size of the output image.
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetTransform (TransformType * transform)
Set the coordinate transformation. Set the coordinate transform to use for resampling. Note that this must be in physical coordinates and it is the output-to-input transform, NOT the input-to-output transform that you might naively expect. By default the filter uses an Identity transform. You must provide a different transform here, before attempting to run the filter, if you do not want to use the default Identity transform.
Definition at line 112 of file animaResampleImageFilter.hxx.
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelImage(), and anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ResampleImages().
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetUseReferenceImage (bool _arg) virtual
template<class TInputImage , class TOutputImage , class TInterpolatorPrecisionType > void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
ThreadedGenerateData
Definition at line 169 of file animaResampleImageFilter.hxx.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::UseReferenceImageOff () virtual
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> virtual void anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::UseReferenceImageOn () virtual
Member Data Documentation
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> const unsigned int anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::ImageDimension = TOutputImage::ImageDimension static
Number of dimensions.
Definition at line 43 of file animaResampleImageFilter.h.
template<class TInputImage, class TOutputImage, class TInterpolatorPrecisionType = double> const unsigned int anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::InputImageDimension = TInputImage::ImageDimension static
Definition at line 45 of file animaResampleImageFilter.h.
The documentation for this class was generated from the following files:
animaResampleImageFilter.h
animaResampleImageFilter.hxx